// Compiler defined macros. Do not include.

#define ADJ_ESTERROR 0x0008
#define ADJ_FREQUENCY 0x0002
#define ADJ_MAXERROR 0x0004
#define ADJ_MICRO 0x1000
#define ADJ_NANO 0x2000
#define ADJ_OFFSET 0x0001
#define ADJ_OFFSET_SINGLESHOT 0x8001
#define ADJ_OFFSET_SS_READ 0xa001
#define ADJ_SETOFFSET 0x0100
#define ADJ_STATUS 0x0010
#define ADJ_TAI 0x0080
#define ADJ_TICK 0x4000
#define ADJ_TIMECONST 0x0020
#define BIG_ENDIAN __BIG_ENDIAN
#define BISHENG_BUILTIN_TYPE_PROXY(NAME) __BISHENG_BUILTIN_TYPE_PROXY_##NAME
#define BUFSIZ 8192
#define BYTE_ORDER __BYTE_ORDER
#define CCEBlockMaxSize 16 * 1024
#define CCELIB_PRINT_COMMON_IMPL_H
#define CCELIB_PRINT_DEVICE_PRINT_RUNTIME_H
#define CCELIB_PRINT_PAYLOAD_H
#define CCELIB_PRINT_PAYLOAD_IMPL_H
#define CCELIB_PRINT_PRINTSTATE_H
#define CCELIB_PRINT_PRINT_H
#define CCELIB_PRINT_TUNNEL_H
#define CCELIB_PRINT_TUNNEL_IMPL_H
#define CCE_AICORE_INTRINSICS_ALIAS
#define CCE_AICORE_INTRINSICS_ALIAS_3510
#define CCE_AICORE_INTRINSICS_TYPES
#define CCE_AICORE_INTRINSICS_TYPES_3510
#define CCE_FALSE 0
#define CCE_FUNC __attribute__((cce_builtin_api, always_inline))[aicore]
#define CCE_GET_VA_INTRINSIC static __attribute__((overloadable, always_inline, cce_empty_func_body))
#define CCE_TRUE 1
#define CLANG_CCELIB_AICORE_H
#define CLANG_CCELIB_H__
#define CLOCKS_PER_SEC ((__clock_t) 1000000)
#define CLOCK_BOOTTIME 7
#define CLOCK_BOOTTIME_ALARM 9
#define CLOCK_MONOTONIC 1
#define CLOCK_MONOTONIC_COARSE 6
#define CLOCK_MONOTONIC_RAW 4
#define CLOCK_PROCESS_CPUTIME_ID 2
#define CLOCK_REALTIME 0
#define CLOCK_REALTIME_ALARM 8
#define CLOCK_REALTIME_COARSE 5
#define CLOCK_TAI 11
#define CLOCK_THREAD_CPUTIME_ID 3
#define CLONE_CHILD_CLEARTID 0x00200000
#define CLONE_CHILD_SETTID 0x01000000
#define CLONE_DETACHED 0x00400000
#define CLONE_FILES 0x00000400
#define CLONE_FS 0x00000200
#define CLONE_IO 0x80000000
#define CLONE_NEWCGROUP 0x02000000
#define CLONE_NEWIPC 0x08000000
#define CLONE_NEWNET 0x40000000
#define CLONE_NEWNS 0x00020000
#define CLONE_NEWPID 0x20000000
#define CLONE_NEWUSER 0x10000000
#define CLONE_NEWUTS 0x04000000
#define CLONE_PARENT 0x00008000
#define CLONE_PARENT_SETTID 0x00100000
#define CLONE_PIDFD 0x00001000
#define CLONE_PTRACE 0x00002000
#define CLONE_SETTLS 0x00080000
#define CLONE_SIGHAND 0x00000800
#define CLONE_SYSVSEM 0x00040000
#define CLONE_THREAD 0x00010000
#define CLONE_UNTRACED 0x00800000
#define CLONE_VFORK 0x00004000
#define CLONE_VM 0x00000100
#define CONSTANT_PADDING CONSTANT_PADDING_Type()
#define CPU_ALLOC(count) __CPU_ALLOC (count)
#define CPU_ALLOC_SIZE(count) __CPU_ALLOC_SIZE (count)
#define CPU_AND(destset,srcset1,srcset2) __CPU_OP_S (sizeof (cpu_set_t), destset, srcset1, srcset2, &)
#define CPU_AND_S(setsize,destset,srcset1,srcset2) __CPU_OP_S (setsize, destset, srcset1, srcset2, &)
#define CPU_CLR(cpu,cpusetp) __CPU_CLR_S (cpu, sizeof (cpu_set_t), cpusetp)
#define CPU_CLR_S(cpu,setsize,cpusetp) __CPU_CLR_S (cpu, setsize, cpusetp)
#define CPU_COUNT(cpusetp) __CPU_COUNT_S (sizeof (cpu_set_t), cpusetp)
#define CPU_COUNT_S(setsize,cpusetp) __CPU_COUNT_S (setsize, cpusetp)
#define CPU_EQUAL(cpusetp1,cpusetp2) __CPU_EQUAL_S (sizeof (cpu_set_t), cpusetp1, cpusetp2)
#define CPU_EQUAL_S(setsize,cpusetp1,cpusetp2) __CPU_EQUAL_S (setsize, cpusetp1, cpusetp2)
#define CPU_FREE(cpuset) __CPU_FREE (cpuset)
#define CPU_ISSET(cpu,cpusetp) __CPU_ISSET_S (cpu, sizeof (cpu_set_t), cpusetp)
#define CPU_ISSET_S(cpu,setsize,cpusetp) __CPU_ISSET_S (cpu, setsize, cpusetp)
#define CPU_OR(destset,srcset1,srcset2) __CPU_OP_S (sizeof (cpu_set_t), destset, srcset1, srcset2, |)
#define CPU_OR_S(setsize,destset,srcset1,srcset2) __CPU_OP_S (setsize, destset, srcset1, srcset2, |)
#define CPU_SET(cpu,cpusetp) __CPU_SET_S (cpu, sizeof (cpu_set_t), cpusetp)
#define CPU_SETSIZE __CPU_SETSIZE
#define CPU_SET_S(cpu,setsize,cpusetp) __CPU_SET_S (cpu, setsize, cpusetp)
#define CPU_XOR(destset,srcset1,srcset2) __CPU_OP_S (sizeof (cpu_set_t), destset, srcset1, srcset2, ^)
#define CPU_XOR_S(setsize,destset,srcset1,srcset2) __CPU_OP_S (setsize, destset, srcset1, srcset2, ^)
#define CPU_ZERO(cpusetp) __CPU_ZERO_S (sizeof (cpu_set_t), cpusetp)
#define CPU_ZERO_S(setsize,cpusetp) __CPU_ZERO_S (setsize, cpusetp)
#define CSIGNAL 0x000000ff
#define DEFINE_BISHENG_BUILTIN_TYPE_PROXY(NAME,BYTE_SIZE) struct [[bisheng::mangling_hint(NAME)]] BISHENG_BUILTIN_TYPE_PROXY(NAME) { BISHENG_BUILTIN_TYPE_PROXY(NAME)() = delete; BISHENG_BUILTIN_TYPE_PROXY(NAME) (const BISHENG_BUILTIN_TYPE_PROXY(NAME) &) = delete; BISHENG_BUILTIN_TYPE_PROXY(NAME) (BISHENG_BUILTIN_TYPE_PROXY(NAME) &&) = delete; BISHENG_BUILTIN_TYPE_PROXY(NAME)(int x) {} private: char Storage[BYTE_SIZE]; }
#define E2BIG 7
#define EACCES 13
#define EADDRINUSE 98
#define EADDRNOTAVAIL 99
#define EADV 68
#define EAFNOSUPPORT 97
#define EAGAIN 11
#define EALREADY 114
#define EBADE 52
#define EBADF 9
#define EBADFD 77
#define EBADMSG 74
#define EBADR 53
#define EBADRQC 56
#define EBADSLT 57
#define EBFONT 59
#define EBUSY 16
#define ECANCELED 125
#define ECHILD 10
#define ECHRNG 44
#define ECOMM 70
#define ECONNABORTED 103
#define ECONNREFUSED 111
#define ECONNRESET 104
#define EDEADLK 35
#define EDEADLOCK EDEADLK
#define EDESTADDRREQ 89
#define EDOM 33
#define EDOTDOT 73
#define EDQUOT 122
#define EEXIST 17
#define EFAULT 14
#define EFBIG 27
#define EHOSTDOWN 112
#define EHOSTUNREACH 113
#define EHWPOISON 133
#define EIDRM 43
#define EILSEQ 84
#define EINPROGRESS 115
#define EINTR 4
#define EINVAL 22
#define EIO 5
#define EISCONN 106
#define EISDIR 21
#define EISNAM 120
#define EKEYEXPIRED 127
#define EKEYREJECTED 129
#define EKEYREVOKED 128
#define EL2HLT 51
#define EL2NSYNC 45
#define EL3HLT 46
#define EL3RST 47
#define ELIBACC 79
#define ELIBBAD 80
#define ELIBEXEC 83
#define ELIBMAX 82
#define ELIBSCN 81
#define ELNRNG 48
#define ELOOP 40
#define EMEDIUMTYPE 124
#define EMFILE 24
#define EMLINK 31
#define EMSGSIZE 90
#define EMULTIHOP 72
#define ENAMETOOLONG 36
#define ENAVAIL 119
#define ENETDOWN 100
#define ENETRESET 102
#define ENETUNREACH 101
#define ENFILE 23
#define ENOANO 55
#define ENOBUFS 105
#define ENOCSI 50
#define ENODATA 61
#define ENODEV 19
#define ENOENT 2
#define ENOEXEC 8
#define ENOKEY 126
#define ENOLCK 37
#define ENOLINK 67
#define ENOMEDIUM 123
#define ENOMEM 12
#define ENOMSG 42
#define ENONET 64
#define ENOPKG 65
#define ENOPROTOOPT 92
#define ENOSPC 28
#define ENOSR 63
#define ENOSTR 60
#define ENOSYS 38
#define ENOTBLK 15
#define ENOTCONN 107
#define ENOTDIR 20
#define ENOTEMPTY 39
#define ENOTNAM 118
#define ENOTRECOVERABLE 131
#define ENOTSOCK 88
#define ENOTSUP EOPNOTSUPP
#define ENOTTY 25
#define ENOTUNIQ 76
#define ENXIO 6
#define EOF (-1)
#define EOPNOTSUPP 95
#define EOVERFLOW 75
#define EOWNERDEAD 130
#define EPERM 1
#define EPFNOSUPPORT 96
#define EPIPE 32
#define EPROTO 71
#define EPROTONOSUPPORT 93
#define EPROTOTYPE 91
#define ERANGE 34
#define EREMCHG 78
#define EREMOTE 66
#define EREMOTEIO 121
#define ERESTART 85
#define ERFKILL 132
#define EROFS 30
#define ESHUTDOWN 108
#define ESOCKTNOSUPPORT 94
#define ESPIPE 29
#define ESRCH 3
#define ESRMNT 69
#define ESTALE 116
#define ESTRPIPE 86
#define ETIME 62
#define ETIMEDOUT 110
#define ETOOMANYREFS 109
#define ETXTBSY 26
#define EUCLEAN 117
#define EUNATCH 49
#define EUSERS 87
#define EWOULDBLOCK EAGAIN
#define EXDEV 18
#define EXFULL 54
#define EXIT_FAILURE 1
#define EXIT_SUCCESS 0
#define FD_CLR(fd,fdsetp) __FD_CLR (fd, fdsetp)
#define FD_ISSET(fd,fdsetp) __FD_ISSET (fd, fdsetp)
#define FD_SET(fd,fdsetp) __FD_SET (fd, fdsetp)
#define FD_SETSIZE __FD_SETSIZE
#define FD_ZERO(fdsetp) __FD_ZERO (fdsetp)
#define FILENAME_MAX 4096
#define FOPEN_MAX 16
#define INT16_C(c) c
#define INT16_MAX (32767)
#define INT16_MIN (-32767-1)
#define INT16_WIDTH 16
#define INT32_C(c) c
#define INT32_MAX (2147483647)
#define INT32_MIN (-2147483647-1)
#define INT32_WIDTH 32
#define INT64_C(c) c ## L
#define INT64_MAX (__INT64_C(9223372036854775807))
#define INT64_MIN (-__INT64_C(9223372036854775807)-1)
#define INT64_WIDTH 64
#define INT8_C(c) c
#define INT8_MAX (127)
#define INT8_MIN (-128)
#define INT8_WIDTH 8
#define INTMAX_C(c) c ## L
#define INTMAX_MAX (__INT64_C(9223372036854775807))
#define INTMAX_MIN (-__INT64_C(9223372036854775807)-1)
#define INTMAX_WIDTH 64
#define INTPTR_MAX (9223372036854775807L)
#define INTPTR_MIN (-9223372036854775807L-1)
#define INTPTR_WIDTH __WORDSIZE
#define INT_FAST16_MAX (9223372036854775807L)
#define INT_FAST16_MIN (-9223372036854775807L-1)
#define INT_FAST16_WIDTH __WORDSIZE
#define INT_FAST32_MAX (9223372036854775807L)
#define INT_FAST32_MIN (-9223372036854775807L-1)
#define INT_FAST32_WIDTH __WORDSIZE
#define INT_FAST64_MAX (__INT64_C(9223372036854775807))
#define INT_FAST64_MIN (-__INT64_C(9223372036854775807)-1)
#define INT_FAST64_WIDTH 64
#define INT_FAST8_MAX (127)
#define INT_FAST8_MIN (-128)
#define INT_FAST8_WIDTH 8
#define INT_LEAST16_MAX (32767)
#define INT_LEAST16_MIN (-32767-1)
#define INT_LEAST16_WIDTH 16
#define INT_LEAST32_MAX (2147483647)
#define INT_LEAST32_MIN (-2147483647-1)
#define INT_LEAST32_WIDTH 32
#define INT_LEAST64_MAX (__INT64_C(9223372036854775807))
#define INT_LEAST64_MIN (-__INT64_C(9223372036854775807)-1)
#define INT_LEAST64_WIDTH 64
#define INT_LEAST8_MAX (127)
#define INT_LEAST8_MIN (-128)
#define INT_LEAST8_WIDTH 8
#define INVALID_VALUE_PADDING_OUTTOUB "The 6th argument can only be NEAREST_PADDING, CONSTANT_PADDING"
#define INVALID_VALUE_PADDING_UBTOUB "The 5th argument can only be NEAREST_PADDING, CONSTANT_PADDING"
#define INVALID_VALUE_PART "The value of PART is not valid"
#define INVALID_VALUE_RS "The value of RS is not valid"
#define INVALID_VALUE_V210_MODE "V210 only support MODE_MERGING and MODE_UNKNOWN"
#define INVALID_VALUE_VSLD "The 4th argument of vsld is not valid"
#define LAUNCH_BOUND(N) __attribute__((cce_launch_bounds(N)))
#define LC_ADDRESS __LC_ADDRESS
#define LC_ADDRESS_MASK (1 << __LC_ADDRESS)
#define LC_ALL __LC_ALL
#define LC_ALL_MASK (LC_CTYPE_MASK | LC_NUMERIC_MASK | LC_TIME_MASK | LC_COLLATE_MASK | LC_MONETARY_MASK | LC_MESSAGES_MASK | LC_PAPER_MASK | LC_NAME_MASK | LC_ADDRESS_MASK | LC_TELEPHONE_MASK | LC_MEASUREMENT_MASK | LC_IDENTIFICATION_MASK )
#define LC_COLLATE __LC_COLLATE
#define LC_COLLATE_MASK (1 << __LC_COLLATE)
#define LC_CTYPE __LC_CTYPE
#define LC_CTYPE_MASK (1 << __LC_CTYPE)
#define LC_GLOBAL_LOCALE ((locale_t) -1L)
#define LC_IDENTIFICATION __LC_IDENTIFICATION
#define LC_IDENTIFICATION_MASK (1 << __LC_IDENTIFICATION)
#define LC_MEASUREMENT __LC_MEASUREMENT
#define LC_MEASUREMENT_MASK (1 << __LC_MEASUREMENT)
#define LC_MESSAGES __LC_MESSAGES
#define LC_MESSAGES_MASK (1 << __LC_MESSAGES)
#define LC_MONETARY __LC_MONETARY
#define LC_MONETARY_MASK (1 << __LC_MONETARY)
#define LC_NAME __LC_NAME
#define LC_NAME_MASK (1 << __LC_NAME)
#define LC_NUMERIC __LC_NUMERIC
#define LC_NUMERIC_MASK (1 << __LC_NUMERIC)
#define LC_PAPER __LC_PAPER
#define LC_PAPER_MASK (1 << __LC_PAPER)
#define LC_TELEPHONE __LC_TELEPHONE
#define LC_TELEPHONE_MASK (1 << __LC_TELEPHONE)
#define LC_TIME __LC_TIME
#define LC_TIME_MASK (1 << __LC_TIME)
#define LITTLE_ENDIAN __LITTLE_ENDIAN
#define L_ctermid 9
#define L_cuserid 9
#define L_tmpnam 20
#define LogBufferPaddingBytes 64
#define MB_CUR_MAX (__ctype_get_mb_cur_max ())
#define MOD_CLKA ADJ_OFFSET_SINGLESHOT
#define MOD_CLKB ADJ_TICK
#define MOD_ESTERROR ADJ_ESTERROR
#define MOD_FREQUENCY ADJ_FREQUENCY
#define MOD_MAXERROR ADJ_MAXERROR
#define MOD_MICRO ADJ_MICRO
#define MOD_NANO ADJ_NANO
#define MOD_OFFSET ADJ_OFFSET
#define MOD_STATUS ADJ_STATUS
#define MOD_TAI ADJ_TAI
#define MOD_TIMECONST ADJ_TIMECONST
#define NEAREST_PADDING NEAREST_PADDING_Type()
#define NFDBITS __NFDBITS
#define NULL __null
#define NumPhysicalPerLogical 3
#define PDP_ENDIAN __PDP_ENDIAN
#define PIPE_ID(v) __attribute__((__pipe_type__(v)))
#define PIPE_LSU1 _Pragma("GCC warning \"'PIPE_LSU1' is deprecated\"") PIPE_MTE1
#define PIPE_LSU2 _Pragma("GCC warning \"'PIPE_LSU2' is deprecated\"") PIPE_MTE2
#define PIPE_LSU3 _Pragma("GCC warning \"'PIPE_LSU3' is deprecated\"") PIPE_MTE3
#define PTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP { { __PTHREAD_MUTEX_INITIALIZER (PTHREAD_MUTEX_ADAPTIVE_NP) } }
#define PTHREAD_ATTR_NO_SIGMASK_NP (-1)
#define PTHREAD_BARRIER_SERIAL_THREAD -1
#define PTHREAD_CANCELED ((void *) -1)
#define PTHREAD_CANCEL_ASYNCHRONOUS PTHREAD_CANCEL_ASYNCHRONOUS
#define PTHREAD_CANCEL_DEFERRED PTHREAD_CANCEL_DEFERRED
#define PTHREAD_CANCEL_DISABLE PTHREAD_CANCEL_DISABLE
#define PTHREAD_CANCEL_ENABLE PTHREAD_CANCEL_ENABLE
#define PTHREAD_COND_INITIALIZER { { {0}, {0}, {0, 0}, {0, 0}, 0, 0, {0, 0} } }
#define PTHREAD_CREATE_DETACHED PTHREAD_CREATE_DETACHED
#define PTHREAD_CREATE_JOINABLE PTHREAD_CREATE_JOINABLE
#define PTHREAD_ERRORCHECK_MUTEX_INITIALIZER_NP { { __PTHREAD_MUTEX_INITIALIZER (PTHREAD_MUTEX_ERRORCHECK_NP) } }
#define PTHREAD_EXPLICIT_SCHED PTHREAD_EXPLICIT_SCHED
#define PTHREAD_INHERIT_SCHED PTHREAD_INHERIT_SCHED
#define PTHREAD_MUTEX_INITIALIZER { { __PTHREAD_MUTEX_INITIALIZER (PTHREAD_MUTEX_TIMED_NP) } }
#define PTHREAD_ONCE_INIT 0
#define PTHREAD_PROCESS_PRIVATE PTHREAD_PROCESS_PRIVATE
#define PTHREAD_PROCESS_SHARED PTHREAD_PROCESS_SHARED
#define PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP { { __PTHREAD_MUTEX_INITIALIZER (PTHREAD_MUTEX_RECURSIVE_NP) } }
#define PTHREAD_RWLOCK_INITIALIZER { { __PTHREAD_RWLOCK_INITIALIZER (PTHREAD_RWLOCK_DEFAULT_NP) } }
#define PTHREAD_RWLOCK_WRITER_NONRECURSIVE_INITIALIZER_NP { { __PTHREAD_RWLOCK_INITIALIZER (PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP) } }
#define PTHREAD_SCOPE_PROCESS PTHREAD_SCOPE_PROCESS
#define PTHREAD_SCOPE_SYSTEM PTHREAD_SCOPE_SYSTEM
#define PTHREAD_STACK_MIN __sysconf (__SC_THREAD_STACK_MIN_VALUE)
#define PTRDIFF_MAX (9223372036854775807L)
#define PTRDIFF_MIN (-9223372036854775807L-1)
#define PTRDIFF_WIDTH __WORDSIZE
#define P_tmpdir "/tmp"
#define RAND_MAX 2147483647
#define RENAME_EXCHANGE (1 << 1)
#define RENAME_NOREPLACE (1 << 0)
#define RENAME_WHITEOUT (1 << 2)
#define RT_CONFIGURE_CALL unsigned int rtConfigureCall(uint32_t numBlocks, void *smDesc = nullptr, void *stream = nullptr);
#define RT_CONFIGURE_CALL_OVERLOAD unsigned int rtConfigureCall(uint32_t numBlocks, void *smDesc, void *stream);
#define SCHED_BATCH 3
#define SCHED_DEADLINE 6
#define SCHED_FIFO 1
#define SCHED_IDLE 5
#define SCHED_ISO 4
#define SCHED_OTHER 0
#define SCHED_RESET_ON_FORK 0x40000000
#define SCHED_RR 2
#define SEEK_CUR 1
#define SEEK_DATA 3
#define SEEK_END 2
#define SEEK_HOLE 4
#define SEEK_SET 0
#define SIG_ATOMIC_MAX (2147483647)
#define SIG_ATOMIC_MIN (-2147483647-1)
#define SIG_ATOMIC_WIDTH 32
#define SIZE_MAX (18446744073709551615UL)
#define SIZE_WIDTH __WORDSIZE
#define STA_CLK 0x8000
#define STA_CLOCKERR 0x1000
#define STA_DEL 0x0020
#define STA_FLL 0x0008
#define STA_FREQHOLD 0x0080
#define STA_INS 0x0010
#define STA_MODE 0x4000
#define STA_NANO 0x2000
#define STA_PLL 0x0001
#define STA_PPSERROR 0x0800
#define STA_PPSFREQ 0x0002
#define STA_PPSJITTER 0x0200
#define STA_PPSSIGNAL 0x0100
#define STA_PPSTIME 0x0004
#define STA_PPSWANDER 0x0400
#define STA_RONLY (STA_PPSSIGNAL | STA_PPSJITTER | STA_PPSWANDER | STA_PPSERROR | STA_CLOCKERR | STA_NANO | STA_MODE | STA_CLK)
#define STA_UNSYNC 0x0040
#define TIMER_ABSTIME 1
#define TIME_UTC 1
#define TMP_MAX 238328
#define UINT16_C(c) c
#define UINT16_MAX (65535)
#define UINT16_WIDTH 16
#define UINT32_C(c) c ## U
#define UINT32_MAX (4294967295U)
#define UINT32_WIDTH 32
#define UINT64_C(c) c ## UL
#define UINT64_MAX (__UINT64_C(18446744073709551615))
#define UINT64_WIDTH 64
#define UINT8_C(c) c
#define UINT8_MAX (255)
#define UINT8_WIDTH 8
#define UINTMAX_C(c) c ## UL
#define UINTMAX_MAX (__UINT64_C(18446744073709551615))
#define UINTMAX_WIDTH 64
#define UINTPTR_MAX (18446744073709551615UL)
#define UINTPTR_WIDTH __WORDSIZE
#define UINT_FAST16_MAX (18446744073709551615UL)
#define UINT_FAST16_WIDTH __WORDSIZE
#define UINT_FAST32_MAX (18446744073709551615UL)
#define UINT_FAST32_WIDTH __WORDSIZE
#define UINT_FAST64_MAX (__UINT64_C(18446744073709551615))
#define UINT_FAST64_WIDTH 64
#define UINT_FAST8_MAX (255)
#define UINT_FAST8_WIDTH 8
#define UINT_LEAST16_MAX (65535)
#define UINT_LEAST16_WIDTH 16
#define UINT_LEAST32_MAX (4294967295U)
#define UINT_LEAST32_WIDTH 32
#define UINT_LEAST64_MAX (__UINT64_C(18446744073709551615))
#define UINT_LEAST64_WIDTH 64
#define UINT_LEAST8_MAX (255)
#define UINT_LEAST8_WIDTH 8
#define VerifyBorder(nextField,maxBuf) if (nextField > maxBuf) { printf("\nWARNING: out of bound! try best to print\n"); return false; }
#define WCHAR_MAX __WCHAR_MAX
#define WCHAR_MIN __WCHAR_MIN
#define WCHAR_WIDTH 32
#define WCONTINUED 8
#define WEOF (0xffffffffu)
#define WEXITED 4
#define WEXITSTATUS(status) __WEXITSTATUS (status)
#define WIFCONTINUED(status) __WIFCONTINUED (status)
#define WIFEXITED(status) __WIFEXITED (status)
#define WIFSIGNALED(status) __WIFSIGNALED (status)
#define WIFSTOPPED(status) __WIFSTOPPED (status)
#define WINT_MAX (4294967295u)
#define WINT_MIN (0u)
#define WINT_WIDTH 32
#define WNOHANG 1
#define WNOWAIT 0x01000000
#define WSTOPPED 2
#define WSTOPSIG(status) __WSTOPSIG (status)
#define WTERMSIG(status) __WTERMSIG (status)
#define WUNTRACED 2
#define _ALLOCATOR_H 1
#define _ALLOCA_H 1
#define _ALLOC_TRAITS_H 1
#define _ASM_GENERIC_ERRNO_BASE_H
#define _ASM_GENERIC_ERRNO_H
#define _ATFILE_SOURCE 1
#define _BACKWARD_BINDERS_H 1
#define _BASIC_STRING_H 1
#define _BASIC_STRING_TCC 1
#define _BITS_ATOMIC_WIDE_COUNTER_H
#define _BITS_BYTESWAP_H 1
#define _BITS_CPU_SET_H 1
#define _BITS_ENDIANNESS_H 1
#define _BITS_ENDIAN_H 1
#define _BITS_ERRNO_H 1
#define _BITS_FLOATN_COMMON_H
#define _BITS_FLOATN_H
#define _BITS_LOCALE_H 1
#define _BITS_PTHREADTYPES_ARCH_H 1
#define _BITS_PTHREADTYPES_COMMON_H 1
#define _BITS_SCHED_H 1
#define _BITS_SETJMP_H 1
#define _BITS_STDINT_INTN_H 1
#define _BITS_STDINT_UINTN_H 1
#define _BITS_STDIO_LIM_H 1
#define _BITS_TIME64_H 1
#define _BITS_TIMEX_H 1
#define _BITS_TIME_H 1
#define _BITS_TYPESIZES_H 1
#define _BITS_TYPES_H 1
#define _BITS_TYPES_LOCALE_T_H 1
#define _BITS_TYPES_STRUCT_SCHED_PARAM 1
#define _BITS_TYPES___LOCALE_T_H 1
#define _BITS_UINTN_IDENTITY_H 1
#define _BITS_WCHAR_H 1
#define _CHAR_TRAITS_H 1
#define _CONCEPT_CHECK_H 1
#define _CPP_TYPE_TRAITS_H 1
#define _CTYPE_H 1
#define _CXXABI_FORCED_H 1
#define _DEFAULT_SOURCE 1
#define _DYNAMIC_STACK_SIZE_SOURCE 1
#define _ENDIAN_H 1
#define _ERRNO_H 1
#define _EXCEPTION_DEFINES_H 1
#define _EXT_ALLOC_TRAITS_H 1
#define _EXT_NUMERIC_TRAITS 1
#define _EXT_TYPE_TRAITS 1
#define _FEATURES_H 1
#define _FUNCTEXCEPT_H 1
#define _FUNCTIONAL_HASH_H 1
#define _GLIBCXX11_DEPRECATED _GLIBCXX_DEPRECATED
#define _GLIBCXX11_DEPRECATED_SUGGEST(ALT) _GLIBCXX_DEPRECATED_SUGGEST(ALT)
#define _GLIBCXX11_USE_C99_COMPLEX 1
#define _GLIBCXX11_USE_C99_MATH 1
#define _GLIBCXX11_USE_C99_STDIO 1
#define _GLIBCXX11_USE_C99_STDLIB 1
#define _GLIBCXX11_USE_C99_WCHAR 1
#define _GLIBCXX14_CONSTEXPR constexpr
#define _GLIBCXX17_CONSTEXPR constexpr
#define _GLIBCXX17_DEPRECATED [[__deprecated__]]
#define _GLIBCXX17_DEPRECATED_SUGGEST(ALT) _GLIBCXX_DEPRECATED_SUGGEST(ALT)
#define _GLIBCXX17_INLINE inline
#define _GLIBCXX20_CONSTEXPR
#define _GLIBCXX20_DEPRECATED(MSG)
#define _GLIBCXX20_DEPRECATED_SUGGEST(ALT)
#define _GLIBCXX98_USE_C99_COMPLEX 1
#define _GLIBCXX98_USE_C99_MATH 1
#define _GLIBCXX98_USE_C99_STDIO 1
#define _GLIBCXX98_USE_C99_STDLIB 1
#define _GLIBCXX98_USE_C99_WCHAR 1
#define _GLIBCXX_ABI_TAG_CXX11 __attribute ((__abi_tag__ ("cxx11")))
#define _GLIBCXX_ALWAYS_INLINE inline __attribute__((__always_inline__))
#define _GLIBCXX_ATOMICITY_H 1
#define _GLIBCXX_ATOMIC_BUILTINS 1
#define _GLIBCXX_ATOMIC_WORD_H 1
#define _GLIBCXX_BEGIN_EXTERN_C extern "C" {
#define _GLIBCXX_BEGIN_NAMESPACE_ALGO
#define _GLIBCXX_BEGIN_NAMESPACE_CONTAINER
#define _GLIBCXX_BEGIN_NAMESPACE_CXX11 namespace __cxx11 {
#define _GLIBCXX_BEGIN_NAMESPACE_LDBL
#define _GLIBCXX_BEGIN_NAMESPACE_LDBL_OR_CXX11 _GLIBCXX_BEGIN_NAMESPACE_CXX11
#define _GLIBCXX_BEGIN_NAMESPACE_VERSION
#define _GLIBCXX_BITS_STD_ABS_H
#define _GLIBCXX_CCTYPE 1
#define _GLIBCXX_CERRNO 1
#define _GLIBCXX_CHARCONV_H 1
#define _GLIBCXX_CLOCALE 1
#define _GLIBCXX_CONST __attribute__ ((__const__))
#define _GLIBCXX_CONSTEXPR constexpr
#define _GLIBCXX_CPU_DEFINES 1
#define _GLIBCXX_CSTDINT 1
#define _GLIBCXX_CSTDIO 1
#define _GLIBCXX_CSTDLIB 1
#define _GLIBCXX_CWCHAR 1
#define _GLIBCXX_CXX_ALLOCATOR_H 1
#define _GLIBCXX_CXX_CONFIG_H 1
#define _GLIBCXX_CXX_LOCALE_H 1
#define _GLIBCXX_C_LOCALE_GNU 1
#define _GLIBCXX_DARWIN_USE_64_BIT_INODE 1
#define _GLIBCXX_DEBUG_ASSERT(_Condition)
#define _GLIBCXX_DEBUG_ASSERTIONS_H 1
#define _GLIBCXX_DEBUG_MACRO_SWITCH_H 1
#define _GLIBCXX_DEBUG_ONLY(_Statement)
#define _GLIBCXX_DEBUG_PEDASSERT(_Condition)
#define _GLIBCXX_DEFAULT_ABI_TAG _GLIBCXX_ABI_TAG_CXX11
#define _GLIBCXX_DEPRECATED __attribute__ ((__deprecated__))
#define _GLIBCXX_DEPRECATED_SUGGEST(ALT) __attribute__ ((__deprecated__ ("use '" ALT "' instead")))
#define _GLIBCXX_DOUBLE_IS_IEEE_BINARY64 1
#define _GLIBCXX_END_EXTERN_C }
#define _GLIBCXX_END_NAMESPACE_ALGO
#define _GLIBCXX_END_NAMESPACE_CONTAINER
#define _GLIBCXX_END_NAMESPACE_CXX11 }
#define _GLIBCXX_END_NAMESPACE_LDBL
#define _GLIBCXX_END_NAMESPACE_LDBL_OR_CXX11 _GLIBCXX_END_NAMESPACE_CXX11
#define _GLIBCXX_END_NAMESPACE_VERSION
#define _GLIBCXX_EXTERN_TEMPLATE 1
#define _GLIBCXX_FAST_MATH 0
#define _GLIBCXX_FLOAT_IS_IEEE_BINARY32 1
#define _GLIBCXX_FORWARD(_Tp,__val) std::forward<_Tp>(__val)
#define _GLIBCXX_FULLY_DYNAMIC_STRING 0
#define _GLIBCXX_FWDREF(_Tp) _Tp&&
#define _GLIBCXX_GCC_GTHR_H
#define _GLIBCXX_GCC_GTHR_POSIX_H
#define _GLIBCXX_GTHREAD_USE_WEAK 0
#define _GLIBCXX_HAS_GTHREADS 1
#define _GLIBCXX_HAS_NESTED_TYPE(_NTYPE) template<typename _Tp, typename = __void_t<>> struct __has_##_NTYPE : false_type { }; template<typename _Tp> struct __has_##_NTYPE<_Tp, __void_t<typename _Tp::_NTYPE>> : true_type { };
#define _GLIBCXX_HAVE_ACOSF 1
#define _GLIBCXX_HAVE_ACOSL 1
#define _GLIBCXX_HAVE_ALIGNED_ALLOC 1
#define _GLIBCXX_HAVE_ARPA_INET_H 1
#define _GLIBCXX_HAVE_ASINF 1
#define _GLIBCXX_HAVE_ASINL 1
#define _GLIBCXX_HAVE_AS_SYMVER_DIRECTIVE 1
#define _GLIBCXX_HAVE_ATAN2F 1
#define _GLIBCXX_HAVE_ATAN2L 1
#define _GLIBCXX_HAVE_ATANF 1
#define _GLIBCXX_HAVE_ATANL 1
#define _GLIBCXX_HAVE_ATOMIC_LOCK_POLICY 1
#define _GLIBCXX_HAVE_ATTRIBUTE_VISIBILITY 1
#define _GLIBCXX_HAVE_AT_QUICK_EXIT 1
#define _GLIBCXX_HAVE_BUILTIN_HAS_UNIQ_OBJ_REP 1
#define _GLIBCXX_HAVE_BUILTIN_IS_AGGREGATE 1
#define _GLIBCXX_HAVE_BUILTIN_IS_CONSTANT_EVALUATED 1
#define _GLIBCXX_HAVE_BUILTIN_IS_SAME 1
#define _GLIBCXX_HAVE_BUILTIN_LAUNDER 1
#define _GLIBCXX_HAVE_CEILF 1
#define _GLIBCXX_HAVE_CEILL 1
#define _GLIBCXX_HAVE_COMPLEX_H 1
#define _GLIBCXX_HAVE_COSF 1
#define _GLIBCXX_HAVE_COSHF 1
#define _GLIBCXX_HAVE_COSHL 1
#define _GLIBCXX_HAVE_COSL 1
#define _GLIBCXX_HAVE_DIRENT_H 1
#define _GLIBCXX_HAVE_DLFCN_H 1
#define _GLIBCXX_HAVE_ENDIAN_H 1
#define _GLIBCXX_HAVE_EXCEPTION_PTR_SINCE_GCC46 1
#define _GLIBCXX_HAVE_EXECINFO_H 1
#define _GLIBCXX_HAVE_EXPF 1
#define _GLIBCXX_HAVE_EXPL 1
#define _GLIBCXX_HAVE_FABSF 1
#define _GLIBCXX_HAVE_FABSL 1
#define _GLIBCXX_HAVE_FCNTL_H 1
#define _GLIBCXX_HAVE_FENV_H 1
#define _GLIBCXX_HAVE_FINITE 1
#define _GLIBCXX_HAVE_FINITEF 1
#define _GLIBCXX_HAVE_FINITEL 1
#define _GLIBCXX_HAVE_FLOAT_H 1
#define _GLIBCXX_HAVE_FLOORF 1
#define _GLIBCXX_HAVE_FLOORL 1
#define _GLIBCXX_HAVE_FMODF 1
#define _GLIBCXX_HAVE_FMODL 1
#define _GLIBCXX_HAVE_FREXPF 1
#define _GLIBCXX_HAVE_FREXPL 1
#define _GLIBCXX_HAVE_GETIPINFO 1
#define _GLIBCXX_HAVE_GETS 1
#define _GLIBCXX_HAVE_HYPOT 1
#define _GLIBCXX_HAVE_HYPOTF 1
#define _GLIBCXX_HAVE_HYPOTL 1
#define _GLIBCXX_HAVE_ICONV 1
#define _GLIBCXX_HAVE_INT64_T 1
#define _GLIBCXX_HAVE_INT64_T_LONG 1
#define _GLIBCXX_HAVE_INTTYPES_H 1
#define _GLIBCXX_HAVE_ISINFF 1
#define _GLIBCXX_HAVE_ISINFL 1
#define _GLIBCXX_HAVE_ISNANF 1
#define _GLIBCXX_HAVE_ISNANL 1
#define _GLIBCXX_HAVE_ISWBLANK 1
#define _GLIBCXX_HAVE_LC_MESSAGES 1
#define _GLIBCXX_HAVE_LDEXPF 1
#define _GLIBCXX_HAVE_LDEXPL 1
#define _GLIBCXX_HAVE_LIBINTL_H 1
#define _GLIBCXX_HAVE_LIMIT_AS 1
#define _GLIBCXX_HAVE_LIMIT_DATA 1
#define _GLIBCXX_HAVE_LIMIT_FSIZE 1
#define _GLIBCXX_HAVE_LIMIT_RSS 1
#define _GLIBCXX_HAVE_LIMIT_VMEM 0
#define _GLIBCXX_HAVE_LINK 1
#define _GLIBCXX_HAVE_LINUX_FUTEX 1
#define _GLIBCXX_HAVE_LINUX_RANDOM_H 1
#define _GLIBCXX_HAVE_LINUX_TYPES_H 1
#define _GLIBCXX_HAVE_LOCALE_H 1
#define _GLIBCXX_HAVE_LOG10F 1
#define _GLIBCXX_HAVE_LOG10L 1
#define _GLIBCXX_HAVE_LOGF 1
#define _GLIBCXX_HAVE_LOGL 1
#define _GLIBCXX_HAVE_MBSTATE_T 1
#define _GLIBCXX_HAVE_MEMALIGN 1
#define _GLIBCXX_HAVE_MEMORY_H 1
#define _GLIBCXX_HAVE_MODF 1
#define _GLIBCXX_HAVE_MODFF 1
#define _GLIBCXX_HAVE_MODFL 1
#define _GLIBCXX_HAVE_NETDB_H 1
#define _GLIBCXX_HAVE_NETINET_IN_H 1
#define _GLIBCXX_HAVE_NETINET_TCP_H 1
#define _GLIBCXX_HAVE_POLL 1
#define _GLIBCXX_HAVE_POLL_H 1
#define _GLIBCXX_HAVE_POSIX_MEMALIGN 1
#define _GLIBCXX_HAVE_POSIX_SEMAPHORE 1
#define _GLIBCXX_HAVE_POWF 1
#define _GLIBCXX_HAVE_POWL 1
#define _GLIBCXX_HAVE_QUICK_EXIT 1
#define _GLIBCXX_HAVE_READLINK 1
#define _GLIBCXX_HAVE_SECURE_GETENV 1
#define _GLIBCXX_HAVE_SETENV 1
#define _GLIBCXX_HAVE_SINCOS 1
#define _GLIBCXX_HAVE_SINCOSF 1
#define _GLIBCXX_HAVE_SINCOSL 1
#define _GLIBCXX_HAVE_SINF 1
#define _GLIBCXX_HAVE_SINHF 1
#define _GLIBCXX_HAVE_SINHL 1
#define _GLIBCXX_HAVE_SINL 1
#define _GLIBCXX_HAVE_SOCKATMARK 1
#define _GLIBCXX_HAVE_SQRTF 1
#define _GLIBCXX_HAVE_SQRTL 1
#define _GLIBCXX_HAVE_STDALIGN_H 1
#define _GLIBCXX_HAVE_STDBOOL_H 1
#define _GLIBCXX_HAVE_STDINT_H 1
#define _GLIBCXX_HAVE_STDLIB_H 1
#define _GLIBCXX_HAVE_STRERROR_L 1
#define _GLIBCXX_HAVE_STRERROR_R 1
#define _GLIBCXX_HAVE_STRINGS_H 1
#define _GLIBCXX_HAVE_STRING_H 1
#define _GLIBCXX_HAVE_STRTOF 1
#define _GLIBCXX_HAVE_STRTOLD 1
#define _GLIBCXX_HAVE_STRUCT_DIRENT_D_TYPE 1
#define _GLIBCXX_HAVE_STRXFRM_L 1
#define _GLIBCXX_HAVE_SYMLINK 1
#define _GLIBCXX_HAVE_SYMVER_SYMBOL_RENAMING_RUNTIME_SUPPORT 1
#define _GLIBCXX_HAVE_SYS_IOCTL_H 1
#define _GLIBCXX_HAVE_SYS_IPC_H 1
#define _GLIBCXX_HAVE_SYS_PARAM_H 1
#define _GLIBCXX_HAVE_SYS_RESOURCE_H 1
#define _GLIBCXX_HAVE_SYS_SDT_H 1
#define _GLIBCXX_HAVE_SYS_SEM_H 1
#define _GLIBCXX_HAVE_SYS_SOCKET_H 1
#define _GLIBCXX_HAVE_SYS_STATVFS_H 1
#define _GLIBCXX_HAVE_SYS_STAT_H 1
#define _GLIBCXX_HAVE_SYS_SYSINFO_H 1
#define _GLIBCXX_HAVE_SYS_TIME_H 1
#define _GLIBCXX_HAVE_SYS_TYPES_H 1
#define _GLIBCXX_HAVE_SYS_UIO_H 1
#define _GLIBCXX_HAVE_S_ISREG 1
#define _GLIBCXX_HAVE_TANF 1
#define _GLIBCXX_HAVE_TANHF 1
#define _GLIBCXX_HAVE_TANHL 1
#define _GLIBCXX_HAVE_TANL 1
#define _GLIBCXX_HAVE_TGMATH_H 1
#define _GLIBCXX_HAVE_TIMESPEC_GET 1
#define _GLIBCXX_HAVE_TLS 1
#define _GLIBCXX_HAVE_TRUNCATE 1
#define _GLIBCXX_HAVE_UCHAR_H 1
#define _GLIBCXX_HAVE_UNISTD_H 1
#define _GLIBCXX_HAVE_USELOCALE 1
#define _GLIBCXX_HAVE_UTIME_H 1
#define _GLIBCXX_HAVE_VFWSCANF 1
#define _GLIBCXX_HAVE_VSWSCANF 1
#define _GLIBCXX_HAVE_VWSCANF 1
#define _GLIBCXX_HAVE_WCHAR_H 1
#define _GLIBCXX_HAVE_WCSTOF 1
#define _GLIBCXX_HAVE_WCTYPE_H 1
#define _GLIBCXX_HAVE_WRITEV 1
#define _GLIBCXX_HAVE___CXA_THREAD_ATEXIT_IMPL 1
#define _GLIBCXX_HOSTED 1
#define _GLIBCXX_ICONV_CONST
#define _GLIBCXX_INLINE_VERSION 0
#define _GLIBCXX_IOSFWD 1
#define _GLIBCXX_LT_OBJDIR ".libs/"
#define _GLIBCXX_MAKE_MOVE_IF_NOEXCEPT_ITERATOR(_Iter) std::__make_move_if_noexcept_iterator(_Iter)
#define _GLIBCXX_MAKE_MOVE_ITERATOR(_Iter) std::make_move_iterator(_Iter)
#define _GLIBCXX_MANGLE_SIZE_T m
#define _GLIBCXX_MOVE(__val) std::move(__val)
#define _GLIBCXX_MOVE3(_Tp,_Up,_Vp) std::move(_Tp, _Up, _Vp)
#define _GLIBCXX_MOVE_BACKWARD3(_Tp,_Up,_Vp) std::move_backward(_Tp, _Up, _Vp)
#define _GLIBCXX_NAMESPACE_CXX11 __cxx11::
#define _GLIBCXX_NAMESPACE_LDBL
#define _GLIBCXX_NAMESPACE_LDBL_OR_CXX11 _GLIBCXX_NAMESPACE_CXX11
#define _GLIBCXX_NATIVE_THREAD_ID pthread_self()
#define _GLIBCXX_NODISCARD [[__nodiscard__]]
#define _GLIBCXX_NOEXCEPT noexcept
#define _GLIBCXX_NOEXCEPT_IF(...) noexcept(__VA_ARGS__)
#define _GLIBCXX_NOEXCEPT_PARM , bool _NE
#define _GLIBCXX_NOEXCEPT_QUAL noexcept (_NE)
#define _GLIBCXX_NORETURN __attribute__ ((__noreturn__))
#define _GLIBCXX_NOTHROW _GLIBCXX_USE_NOEXCEPT
#define _GLIBCXX_NO_OBSOLETE_ISINF_ISNAN_DYNAMIC __GLIBC_PREREQ(2,23)
#define _GLIBCXX_NUM_CATEGORIES 6
#define _GLIBCXX_OS_DEFINES 1
#define _GLIBCXX_PACKAGE_BUGREPORT ""
#define _GLIBCXX_PACKAGE_NAME "package-unused"
#define _GLIBCXX_PACKAGE_STRING "package-unused version-unused"
#define _GLIBCXX_PACKAGE_TARNAME "libstdc++"
#define _GLIBCXX_PACKAGE_URL ""
#define _GLIBCXX_PACKAGE__GLIBCXX_VERSION "version-unused"
#define _GLIBCXX_POSTYPES_H 1
#define _GLIBCXX_PREDEFINED_OPS_H 1
#define _GLIBCXX_PSEUDO_VISIBILITY(V)
#define _GLIBCXX_PURE __attribute__ ((__pure__))
#define _GLIBCXX_RANGE_ACCESS_H 1
#define _GLIBCXX_READ_MEM_BARRIER __atomic_thread_fence (__ATOMIC_ACQUIRE)
#define _GLIBCXX_RELEASE 11
#define _GLIBCXX_RES_LIMITS 1
#define _GLIBCXX_STDC_HEADERS 1
#define _GLIBCXX_STDIO_EOF -1
#define _GLIBCXX_STDIO_SEEK_CUR 1
#define _GLIBCXX_STDIO_SEEK_END 2
#define _GLIBCXX_STD_A std
#define _GLIBCXX_STD_C std
#define _GLIBCXX_STRING 1
#define _GLIBCXX_STRING_VIEW 1
#define _GLIBCXX_STRING_VIEW_TCC 1
#define _GLIBCXX_SYMVER 1
#define _GLIBCXX_SYMVER_GNU 1
#define _GLIBCXX_SYNCHRONIZATION_HAPPENS_AFTER(A)
#define _GLIBCXX_SYNCHRONIZATION_HAPPENS_BEFORE(A)
#define _GLIBCXX_THROW(_EXC)
#define _GLIBCXX_THROW_OR_ABORT(_EXC) (throw (_EXC))
#define _GLIBCXX_TXN_SAFE
#define _GLIBCXX_TXN_SAFE_DYN
#define _GLIBCXX_TYPE_TRAITS 1
#define _GLIBCXX_USE_ALLOCATOR_NEW 1
#define _GLIBCXX_USE_C11_UCHAR_CXX11 1
#define _GLIBCXX_USE_C99 1
#define _GLIBCXX_USE_C99_COMPLEX _GLIBCXX11_USE_C99_COMPLEX
#define _GLIBCXX_USE_C99_COMPLEX_TR1 1
#define _GLIBCXX_USE_C99_CTYPE_TR1 1
#define _GLIBCXX_USE_C99_FENV_TR1 1
#define _GLIBCXX_USE_C99_INTTYPES_TR1 1
#define _GLIBCXX_USE_C99_INTTYPES_WCHAR_T_TR1 1
#define _GLIBCXX_USE_C99_MATH _GLIBCXX11_USE_C99_MATH
#define _GLIBCXX_USE_C99_MATH_TR1 1
#define _GLIBCXX_USE_C99_STDINT_TR1 1
#define _GLIBCXX_USE_C99_STDIO _GLIBCXX11_USE_C99_STDIO
#define _GLIBCXX_USE_C99_STDLIB _GLIBCXX11_USE_C99_STDLIB
#define _GLIBCXX_USE_C99_WCHAR _GLIBCXX11_USE_C99_WCHAR
#define _GLIBCXX_USE_CLOCK_MONOTONIC 1
#define _GLIBCXX_USE_CLOCK_REALTIME 1
#define _GLIBCXX_USE_CONSTEXPR constexpr
#define _GLIBCXX_USE_CXX11_ABI 1
#define _GLIBCXX_USE_DECIMAL_FLOAT 1
#define _GLIBCXX_USE_DEPRECATED 1
#define _GLIBCXX_USE_DEV_RANDOM 1
#define _GLIBCXX_USE_DUAL_ABI 1
#define _GLIBCXX_USE_FCHMOD 1
#define _GLIBCXX_USE_FCHMODAT 1
#define _GLIBCXX_USE_GETTIMEOFDAY 1
#define _GLIBCXX_USE_GET_NPROCS 1
#define _GLIBCXX_USE_INT128 1
#define _GLIBCXX_USE_LFS 1
#define _GLIBCXX_USE_LONG_LONG 1
#define _GLIBCXX_USE_LSTAT 1
#define _GLIBCXX_USE_NANOSLEEP 1
#define _GLIBCXX_USE_NLS 1
#define _GLIBCXX_USE_NOEXCEPT noexcept
#define _GLIBCXX_USE_PTHREAD_COND_CLOCKWAIT 1
#define _GLIBCXX_USE_PTHREAD_MUTEX_CLOCKLOCK 1
#define _GLIBCXX_USE_PTHREAD_RWLOCK_CLOCKLOCK 1
#define _GLIBCXX_USE_PTHREAD_RWLOCK_T 1
#define _GLIBCXX_USE_RANDOM_TR1 1
#define _GLIBCXX_USE_REALPATH 1
#define _GLIBCXX_USE_SCHED_YIELD 1
#define _GLIBCXX_USE_SC_NPROCESSORS_ONLN 1
#define _GLIBCXX_USE_SENDFILE 1
#define _GLIBCXX_USE_STD_SPEC_FUNCS 1
#define _GLIBCXX_USE_ST_MTIM 1
#define _GLIBCXX_USE_TBB_PAR_BACKEND __has_include(<tbb/tbb.h>)
#define _GLIBCXX_USE_TMPNAM 1
#define _GLIBCXX_USE_UTIME 1
#define _GLIBCXX_USE_UTIMENSAT 1
#define _GLIBCXX_USE_WCHAR_T 1
#define _GLIBCXX_USE_WEAK_REF __GXX_WEAK__
#define _GLIBCXX_VERBOSE 1
#define _GLIBCXX_VISIBILITY(V) __attribute__ ((__visibility__ (#V)))
#define _GLIBCXX_WEAK_DEFINITION
#define _GLIBCXX_WRITE_MEM_BARRIER __atomic_thread_fence (__ATOMIC_RELEASE)
#define _GLIBCXX_X86_RDRAND 1
#define _GLIBCXX_X86_RDSEED 1
#define _GNU_SOURCE 1
#define _GTHREAD_USE_MUTEX_TIMEDLOCK 1
#define _HASH_BYTES_H 1
#define _INITIALIZER_LIST
#define _IOFBF 0
#define _IOLBF 1
#define _IONBF 2
#define _IO_EOF_SEEN 0x0010
#define _IO_ERR_SEEN 0x0020
#define _IO_USER_LOCK 0x8000
#define _ISOC11_SOURCE 1
#define _ISOC2X_SOURCE 1
#define _ISOC95_SOURCE 1
#define _ISOC99_SOURCE 1
#define _ISbit(bit) ((bit) < 8 ? ((1 << (bit)) << 8) : ((1 << (bit)) >> 8))
#define _LARGEFILE64_SOURCE 1
#define _LARGEFILE_SOURCE 1
#define _LOCALE_FWD_H 1
#define _LOCALE_H 1
#define _LP64 1
#define _MEMORYFWD_H 1
#define _MOVE_H 1
#define _NEW
#define _NEW_ALLOCATOR_H 1
#define _OSTREAM_INSERT_H 1
#define _POSIX_C_SOURCE 200809L
#define _POSIX_SOURCE 1
#define _PRINTF_NAN_LEN_MAX 4
#define _PSTL_ASSERT(_Condition) __glibcxx_assert(_Condition)
#define _PSTL_ASSERT_MSG(_Condition,_Message) __glibcxx_assert(_Condition)
#define _PSTL_CLANG_VERSION (__clang_major__ * 10000 + __clang_minor__ * 100 + __clang_patchlevel__)
#define _PSTL_CONFIG_H
#define _PSTL_CPP11_STD_ROTATE_BROKEN ((__GLIBCXX__ && __GLIBCXX__ < 20150716) || (_MSC_VER && _MSC_VER < 1800))
#define _PSTL_CPP14_2RANGE_MISMATCH_EQUAL_PRESENT (_MSC_VER >= 1900 || __cplusplus >= 201300L || __cpp_lib_robust_nonmodifying_seq_ops == 201304)
#define _PSTL_CPP14_INTEGER_SEQUENCE_PRESENT (_MSC_VER >= 1900 || __cplusplus >= 201402L)
#define _PSTL_CPP14_MAKE_REVERSE_ITERATOR_PRESENT (_MSC_VER >= 1900 || __cplusplus >= 201402L || __cpp_lib_make_reverse_iterator == 201402)
#define _PSTL_CPP14_VARIABLE_TEMPLATES_PRESENT (!__INTEL_COMPILER || __INTEL_COMPILER >= 1700) && (_MSC_FULL_VER >= 190023918 || __cplusplus >= 201402L)
#define _PSTL_CPP17_EXECUTION_POLICIES_PRESENT (_MSC_VER >= 1912)
#define _PSTL_EARLYEXIT_PRESENT (__INTEL_COMPILER >= 1800)
#define _PSTL_GCC_VERSION (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__)
#define _PSTL_HIDE_FROM_ABI_POP
#define _PSTL_HIDE_FROM_ABI_PUSH
#define _PSTL_ICC_18_OMP_SIMD_BROKEN (__INTEL_COMPILER == 1800)
#define _PSTL_MONOTONIC_PRESENT (__INTEL_COMPILER >= 1800)
#define _PSTL_PAR_BACKEND_SERIAL
#define _PSTL_PRAGMA(x) _Pragma(# x)
#define _PSTL_PRAGMA_DECLARE_REDUCTION(NAME,OP) _PSTL_PRAGMA(omp declare reduction(NAME:OP : omp_out(omp_in)) initializer(omp_priv = omp_orig))
#define _PSTL_PRAGMA_DECLARE_SIMD _PSTL_PRAGMA(omp declare simd)
#define _PSTL_PRAGMA_FORCEINLINE
#define _PSTL_PRAGMA_LOCATION " [Parallel STL message]: "
#define _PSTL_PRAGMA_MESSAGE(x)
#define _PSTL_PRAGMA_MESSAGE_IMPL(x) _PSTL_PRAGMA(message(_PSTL_STRING_CONCAT(_PSTL_PRAGMA_LOCATION, x)))
#define _PSTL_PRAGMA_MESSAGE_POLICIES(x)
#define _PSTL_PRAGMA_SIMD _PSTL_PRAGMA(omp simd)
#define _PSTL_PRAGMA_SIMD_EARLYEXIT
#define _PSTL_PRAGMA_SIMD_EXCLUSIVE_SCAN(PRM)
#define _PSTL_PRAGMA_SIMD_INCLUSIVE_SCAN(PRM)
#define _PSTL_PRAGMA_SIMD_ORDERED_MONOTONIC(PRM)
#define _PSTL_PRAGMA_SIMD_ORDERED_MONOTONIC_2ARGS(PRM1,PRM2)
#define _PSTL_PRAGMA_SIMD_REDUCTION(PRM) _PSTL_PRAGMA(omp simd reduction(PRM))
#define _PSTL_PRAGMA_SIMD_SCAN(PRM)
#define _PSTL_PRAGMA_VECTOR_UNALIGNED
#define _PSTL_STRING(x) _PSTL_STRING_AUX(x)
#define _PSTL_STRING_AUX(x) #x
#define _PSTL_STRING_CONCAT(x,y) x #y
#define _PSTL_UDR_PRESENT 0
#define _PSTL_UDS_PRESENT (__INTEL_COMPILER >= 1900 && __INTEL_COMPILER_BUILD_DATE >= 20180626)
#define _PSTL_USAGE_WARNINGS 0
#define _PSTL_USE_NONTEMPORAL_STORES_IF_ALLOWED
#define _PSTL_VERSION 12000
#define _PSTL_VERSION_MAJOR (_PSTL_VERSION / 1000)
#define _PSTL_VERSION_MINOR ((_PSTL_VERSION % 1000) / 10)
#define _PSTL_VERSION_PATCH (_PSTL_VERSION % 10)
#define _PTHREAD_H 1
#define _PTRDIFF_T
#define _PTR_TRAITS_H 1
#define _RWLOCK_INTERNAL_H
#define _SCHED_H 1
#define _SIGSET_NWORDS (1024 / (8 * sizeof (unsigned long int)))
#define _SIZE_T
#define _STDC_PREDEF_H 1
#define _STDINT_H 1
#define _STDIO_H 1
#define _STDLIB_H 1
#define _STL_ALGOBASE_H 1
#define _STL_CONSTRUCT_H 1
#define _STL_FUNCTION_H 1
#define _STL_ITERATOR_BASE_FUNCS_H 1
#define _STL_ITERATOR_BASE_TYPES_H 1
#define _STL_ITERATOR_H 1
#define _STL_PAIR_H 1
#define _STRINGFWD_H 1
#define _STRING_CONVERSIONS_H 1
#define _STRUCT_TIMESPEC 1
#define _SYS_CDEFS_H 1
#define _SYS_SELECT_H 1
#define _SYS_SINGLE_THREADED_H
#define _SYS_TYPES_H 1
#define _THREAD_MUTEX_INTERNAL_H 1
#define _THREAD_SHARED_TYPES_H 1
#define _TIME_H 1
#define _VA_LIST
#define _VA_LIST_DEFINED
#define _WCHAR_H 1
#define _WINT_T 1
#define _XOPEN_SOURCE 700
#define _XOPEN_SOURCE_EXTENDED 1
#define __ASMNAME(cname) __ASMNAME2 (__USER_LABEL_PREFIX__, cname)
#define __ASMNAME2(prefix,cname) __STRING (prefix) cname
#define __ATOMIC_ACQUIRE 2
#define __ATOMIC_ACQ_REL 4
#define __ATOMIC_CONSUME 1
#define __ATOMIC_RELAXED 0
#define __ATOMIC_RELEASE 3
#define __ATOMIC_SEQ_CST 5
#define __BEGIN_DECLS extern "C" {
#define __BIGGEST_ALIGNMENT__ 8
#define __BIG_ENDIAN 4321
#define __BITINT_MAXWIDTH__ 128
#define __BIT_TYPES_DEFINED__ 1
#define __BLKCNT64_T_TYPE __SQUAD_TYPE
#define __BLKCNT_T_TYPE __SYSCALL_SLONG_TYPE
#define __BLKSIZE_T_TYPE __SYSCALL_SLONG_TYPE
#define __BOOL_WIDTH__ 8
#define __BTB_BASE_ 1024
#define __BYTE_ORDER __LITTLE_ENDIAN
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __CCE_AICORE_SUPPORT_SIMT__ 1
#define __CCE_AICORE__ 310
#define __CCE_ARCH__ 100
#define __CCE_BUILTIN_VARS_H
#define __CCE_DEFINES_H__
#define __CCE_ENABLE_PRINT_AICORE_CUBE__ 1
#define __CCE_ENABLE_PRINT_AICORE__ 1
#define __CCE_ENABLE_PRINT_FOUND_CANN__ 1
#define __CCE_ENABLE_PRINT__ 1
#define __CCE_GET_IMM 1
#define __CCE_INTRINSICS_H__
#define __CCE_IS_AICORE__ 1
#define __CCE_NEED_ADDR_TRANS 1
#define __CCE_RUNTIME_WRAPPER_H__
#define __CCE_TYPES_H__
#define __CCE__ 1
#define __CFLOAT32 _Complex float
#define __CFLOAT32X _Complex double
#define __CFLOAT64 _Complex double
#define __CFLOAT64X _Complex long double
#define __CHAR16_TYPE__ unsigned short
#define __CHAR32_TYPE__ unsigned int
#define __CHAR_BIT__ 8
#define __CLANG_ATOMIC_BOOL_LOCK_FREE 2
#define __CLANG_ATOMIC_CHAR16_T_LOCK_FREE 2
#define __CLANG_ATOMIC_CHAR32_T_LOCK_FREE 2
#define __CLANG_ATOMIC_CHAR_LOCK_FREE 2
#define __CLANG_ATOMIC_INT_LOCK_FREE 2
#define __CLANG_ATOMIC_LLONG_LOCK_FREE 2
#define __CLANG_ATOMIC_LONG_LOCK_FREE 2
#define __CLANG_ATOMIC_POINTER_LOCK_FREE 2
#define __CLANG_ATOMIC_SHORT_LOCK_FREE 2
#define __CLANG_ATOMIC_WCHAR_T_LOCK_FREE 2
#define __CLANG_CCE_AICORE_FUNCTIONS_3510_H__
#define __CLANG_CCE_AICORE_FUNCTIONS_H__
#define __CLANG_CCE_AICPU_NEON_H__
#define __CLANG_CCE_RUNTIME_H__
#define __CLANG_CCE_SIMT_BUILTIN_VARS_H__
#define __CLANG_CCE_SIMT_H__
#define __CLANG_CCE_SIMT_INTRINSICS_3510_H__
#define __CLANG_CCE_SIMT_INTRINSICS_H__
#define __CLANG_CCE_VECTOR_INTRINSICS_3510_H__
#define __CLANG_CCE_VECTOR_INTRINSICS_H
#define __CLANG_CCE_VECTOR_TYPES_3510_H
#define __CLANG_CCE_VECTOR_TYPES_H
#define __CLANG_MAX_ALIGN_T_DEFINED
#define __CLANG_STDINT_H
#define __CLOCKID_T_TYPE __S32_TYPE
#define __CLOCK_T_TYPE __SYSCALL_SLONG_TYPE
#define __COMPAR_FN_T
#define __CONCAT(x,y) x ## y
#define __CONSTANT_CFSTRINGS__ 1
#define __CPUELT(cpu) ((cpu) / __NCPUBITS)
#define __CPUMASK(cpu) ((__cpu_mask) 1 << ((cpu) % __NCPUBITS))
#define __CPU_ALLOC(count) __sched_cpualloc (count)
#define __CPU_ALLOC_SIZE(count) ((((count) + __NCPUBITS - 1) / __NCPUBITS) * sizeof (__cpu_mask))
#define __CPU_CLR_S(cpu,setsize,cpusetp) (__extension__ ({ size_t __cpu = (cpu); __cpu / 8 < (setsize) ? (((__cpu_mask *) ((cpusetp)->__bits))[__CPUELT (__cpu)] &= ~__CPUMASK (__cpu)) : 0; }))
#define __CPU_COUNT_S(setsize,cpusetp) __sched_cpucount (setsize, cpusetp)
#define __CPU_EQUAL_S(setsize,cpusetp1,cpusetp2) (__builtin_memcmp (cpusetp1, cpusetp2, setsize) == 0)
#define __CPU_FREE(cpuset) __sched_cpufree (cpuset)
#define __CPU_ISSET_S(cpu,setsize,cpusetp) (__extension__ ({ size_t __cpu = (cpu); __cpu / 8 < (setsize) ? ((((const __cpu_mask *) ((cpusetp)->__bits))[__CPUELT (__cpu)] & __CPUMASK (__cpu))) != 0 : 0; }))
#define __CPU_MASK_TYPE __SYSCALL_ULONG_TYPE
#define __CPU_OP_S(setsize,destset,srcset1,srcset2,op) (__extension__ ({ cpu_set_t *__dest = (destset); const __cpu_mask *__arr1 = (srcset1)->__bits; const __cpu_mask *__arr2 = (srcset2)->__bits; size_t __imax = (setsize) / sizeof (__cpu_mask); size_t __i; for (__i = 0; __i < __imax; ++__i) ((__cpu_mask *) __dest->__bits)[__i] = __arr1[__i] op __arr2[__i]; __dest; }))
#define __CPU_SETSIZE 1024
#define __CPU_SET_S(cpu,setsize,cpusetp) (__extension__ ({ size_t __cpu = (cpu); __cpu / 8 < (setsize) ? (((__cpu_mask *) ((cpusetp)->__bits))[__CPUELT (__cpu)] |= __CPUMASK (__cpu)) : 0; }))
#define __CPU_ZERO_S(setsize,cpusetp) do __builtin_memset (cpusetp, '\0', setsize); while (0)
#define __CUBE_A_BASE 0
#define __CUBE_A_SIZE 65536
#define __CUBE_BUF_BASE 0
#define __CUBE_BUF_SIZE 1048576
#define __CUBE_B_BASE 0
#define __CUBE_B_SIZE 65536
#define __CUBE_C_BASE 0
#define __CUBE_C_SIZE 262144
#define __DADDR_T_TYPE __S32_TYPE
#define __DAV_C310_CUBE__ 1
#define __DAV_C310__ 1
#define __DAV_CUBE__ 1
#define __DBL_DECIMAL_DIG__ 17
#define __DBL_DENORM_MIN__ 4.9406564584124654e-324
#define __DBL_DIG__ 15
#define __DBL_EPSILON__ 2.2204460492503131e-16
#define __DBL_HAS_DENORM__ 1
#define __DBL_HAS_INFINITY__ 1
#define __DBL_HAS_QUIET_NAN__ 1
#define __DBL_MANT_DIG__ 53
#define __DBL_MAX_10_EXP__ 308
#define __DBL_MAX_EXP__ 1024
#define __DBL_MAX__ 1.7976931348623157e+308
#define __DBL_MIN_10_EXP__ (-307)
#define __DBL_MIN_EXP__ (-1021)
#define __DBL_MIN__ 2.2250738585072014e-308
#define __DECIMAL_DIG__ __LDBL_DECIMAL_DIG__
#define __DEPRECATED 1
#define __DEV_T_TYPE __UQUAD_TYPE
#define __ELF__ 1
#define __END_DECLS }
#define __EXCEPTIONS 1
#define __EXCEPTION_H 1
#define __FB_BASE_ 0
#define __FB_SIZE 0
#define __FDS_BITS(set) ((set)->fds_bits)
#define __FD_CLR(d,s) ((void) (__FDS_BITS (s)[__FD_ELT(d)] &= ~__FD_MASK(d)))
#define __FD_ELT(d) ((d) / __NFDBITS)
#define __FD_ISSET(d,s) ((__FDS_BITS (s)[__FD_ELT (d)] & __FD_MASK (d)) != 0)
#define __FD_MASK(d) ((__fd_mask) (1UL << ((d) % __NFDBITS)))
#define __FD_SET(d,s) ((void) (__FDS_BITS (s)[__FD_ELT(d)] |= __FD_MASK(d)))
#define __FD_SETSIZE 1024
#define __FD_ZERO(s) do { unsigned int __i; fd_set *__arr = (s); for (__i = 0; __i < sizeof (fd_set) / sizeof (__fd_mask); ++__i) __FDS_BITS (__arr)[__i] = 0; } while (0)
#define __FILE_defined 1
#define __FINITE_MATH_ONLY__ 0
#define __FLOAT_WORD_ORDER __BYTE_ORDER
#define __FLT_DECIMAL_DIG__ 9
#define __FLT_DENORM_MIN__ 1.40129846e-45F
#define __FLT_DIG__ 6
#define __FLT_EPSILON__ 1.19209290e-7F
#define __FLT_HAS_DENORM__ 1
#define __FLT_HAS_INFINITY__ 1
#define __FLT_HAS_QUIET_NAN__ 1
#define __FLT_MANT_DIG__ 24
#define __FLT_MAX_10_EXP__ 38
#define __FLT_MAX_EXP__ 128
#define __FLT_MAX__ 3.40282347e+38F
#define __FLT_MIN_10_EXP__ (-37)
#define __FLT_MIN_EXP__ (-125)
#define __FLT_MIN__ 1.17549435e-38F
#define __FLT_RADIX__ 2
#define __FSBLKCNT64_T_TYPE __UQUAD_TYPE
#define __FSBLKCNT_T_TYPE __SYSCALL_ULONG_TYPE
#define __FSFILCNT64_T_TYPE __UQUAD_TYPE
#define __FSFILCNT_T_TYPE __SYSCALL_ULONG_TYPE
#define __FSID_T_TYPE struct { int __val[2]; }
#define __FSWORD_T_TYPE __SYSCALL_SLONG_TYPE
#define __GCC_ATOMIC_BOOL_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR32_T_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR_LOCK_FREE 2
#define __GCC_ATOMIC_INT_LOCK_FREE 2
#define __GCC_ATOMIC_LLONG_LOCK_FREE 2
#define __GCC_ATOMIC_LONG_LOCK_FREE 2
#define __GCC_ATOMIC_POINTER_LOCK_FREE 2
#define __GCC_ATOMIC_SHORT_LOCK_FREE 2
#define __GCC_ATOMIC_TEST_AND_SET_TRUEVAL 1
#define __GCC_ATOMIC_WCHAR_T_LOCK_FREE 2
#define __GCC_HAVE_DWARF2_CFI_ASM 1
#define __GID_T_TYPE __U32_TYPE
#define __GLIBCXX__ 20230528
#define __GLIBC_MINOR__ 35
#define __GLIBC_PREREQ(maj,min) ((__GLIBC__ << 16) + __GLIBC_MINOR__ >= ((maj) << 16) + (min))
#define __GLIBC_USE(F) __GLIBC_USE_ ## F
#define __GLIBC_USE_DEPRECATED_GETS 0
#define __GLIBC_USE_DEPRECATED_SCANF 0
#define __GLIBC_USE_IEC_60559_BFP_EXT 1
#define __GLIBC_USE_IEC_60559_BFP_EXT_C2X 1
#define __GLIBC_USE_IEC_60559_EXT 1
#define __GLIBC_USE_IEC_60559_FUNCS_EXT 1
#define __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X 1
#define __GLIBC_USE_IEC_60559_TYPES_EXT 1
#define __GLIBC_USE_ISOC2X 1
#define __GLIBC_USE_LIB_EXT2 1
#define __GLIBC__ 2
#define __GNUC_GNU_INLINE__ 1
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 1
#define __GNUC_PREREQ(maj,min) ((__GNUC__ << 16) + __GNUC_MINOR__ >= ((maj) << 16) + (min))
#define __GNUC_VA_LIST 1
#define __GNUC__ 4
#define __GNUG__ 4
#define __GNU_LIBRARY__ 6
#define __GTHREADS 1
#define __GTHREADS_CXX0X 1
#define __GTHREAD_COND_INIT PTHREAD_COND_INITIALIZER
#define __GTHREAD_HAS_COND 1
#define __GTHREAD_MUTEX_INIT PTHREAD_MUTEX_INITIALIZER
#define __GTHREAD_MUTEX_INIT_FUNCTION __gthread_mutex_init_function
#define __GTHREAD_ONCE_INIT PTHREAD_ONCE_INIT
#define __GTHREAD_RECURSIVE_MUTEX_INIT PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP
#define __GTHREAD_TIME_INIT {0,0}
#define __GXX_ABI_VERSION 1002
#define __GXX_EXPERIMENTAL_CXX0X__ 1
#define __GXX_RTTI 1
#define __GXX_WEAK__ 1
#define __HAVE_DISTINCT_FLOAT128 0
#define __HAVE_DISTINCT_FLOAT128X __HAVE_FLOAT128X
#define __HAVE_DISTINCT_FLOAT16 __HAVE_FLOAT16
#define __HAVE_DISTINCT_FLOAT32 0
#define __HAVE_DISTINCT_FLOAT32X 0
#define __HAVE_DISTINCT_FLOAT64 0
#define __HAVE_DISTINCT_FLOAT64X 0
#define __HAVE_FLOAT128 0
#define __HAVE_FLOAT128X 0
#define __HAVE_FLOAT128_UNLIKE_LDBL (__HAVE_DISTINCT_FLOAT128 && __LDBL_MANT_DIG__ != 113)
#define __HAVE_FLOAT16 0
#define __HAVE_FLOAT32 1
#define __HAVE_FLOAT32X 1
#define __HAVE_FLOAT64 1
#define __HAVE_FLOAT64X 1
#define __HAVE_FLOAT64X_LONG_DOUBLE 1
#define __HAVE_FLOATN_NOT_TYPEDEF 0
#define __HAVE_GENERIC_SELECTION 0
#define __HiIPU__ 1
#define __ID_T_TYPE __U32_TYPE
#define __INO64_T_TYPE __UQUAD_TYPE
#define __INO_T_MATCHES_INO64_T 1
#define __INO_T_TYPE __SYSCALL_ULONG_TYPE
#define __INT16_C_SUFFIX__
#define __INT16_FMTd__ "hd"
#define __INT16_FMTi__ "hi"
#define __INT16_MAX__ 32767
#define __INT16_TYPE__ short
#define __INT32_C_SUFFIX__
#define __INT32_FMTd__ "d"
#define __INT32_FMTi__ "i"
#define __INT32_MAX__ 2147483647
#define __INT32_TYPE__ int
#define __INT64_C(c) c ## L
#define __INT64_C_SUFFIX__ L
#define __INT64_FMTd__ "ld"
#define __INT64_FMTi__ "li"
#define __INT64_MAX__ 9223372036854775807L
#define __INT64_TYPE__ long int
#define __INT8_C_SUFFIX__
#define __INT8_FMTd__ "hhd"
#define __INT8_FMTi__ "hhi"
#define __INT8_MAX__ 127
#define __INT8_TYPE__ signed char
#define __INTMAX_C_SUFFIX__ L
#define __INTMAX_FMTd__ "ld"
#define __INTMAX_FMTi__ "li"
#define __INTMAX_MAX__ 9223372036854775807L
#define __INTMAX_TYPE__ long int
#define __INTMAX_WIDTH__ 64
#define __INTPTR_FMTd__ "ld"
#define __INTPTR_FMTi__ "li"
#define __INTPTR_MAX__ 9223372036854775807L
#define __INTPTR_TYPE__ long int
#define __INTPTR_WIDTH__ 64
#define __INT_FAST16_FMTd__ "hd"
#define __INT_FAST16_FMTi__ "hi"
#define __INT_FAST16_MAX__ 32767
#define __INT_FAST16_TYPE__ short
#define __INT_FAST16_WIDTH__ 16
#define __INT_FAST32_FMTd__ "d"
#define __INT_FAST32_FMTi__ "i"
#define __INT_FAST32_MAX__ 2147483647
#define __INT_FAST32_TYPE__ int
#define __INT_FAST32_WIDTH__ 32
#define __INT_FAST64_FMTd__ "ld"
#define __INT_FAST64_FMTi__ "li"
#define __INT_FAST64_MAX__ 9223372036854775807L
#define __INT_FAST64_TYPE__ long int
#define __INT_FAST64_WIDTH__ 64
#define __INT_FAST8_FMTd__ "hhd"
#define __INT_FAST8_FMTi__ "hhi"
#define __INT_FAST8_MAX__ 127
#define __INT_FAST8_TYPE__ signed char
#define __INT_FAST8_WIDTH__ 8
#define __INT_LEAST16_FMTd__ "hd"
#define __INT_LEAST16_FMTi__ "hi"
#define __INT_LEAST16_MAX__ 32767
#define __INT_LEAST16_TYPE__ short
#define __INT_LEAST16_WIDTH__ 16
#define __INT_LEAST32_FMTd__ "d"
#define __INT_LEAST32_FMTi__ "i"
#define __INT_LEAST32_MAX__ 2147483647
#define __INT_LEAST32_TYPE__ int
#define __INT_LEAST32_WIDTH__ 32
#define __INT_LEAST64_FMTd__ "ld"
#define __INT_LEAST64_FMTi__ "li"
#define __INT_LEAST64_MAX__ 9223372036854775807L
#define __INT_LEAST64_TYPE__ long int
#define __INT_LEAST64_WIDTH__ 64
#define __INT_LEAST8_FMTd__ "hhd"
#define __INT_LEAST8_FMTi__ "hhi"
#define __INT_LEAST8_MAX__ 127
#define __INT_LEAST8_TYPE__ signed char
#define __INT_LEAST8_WIDTH__ 8
#define __INT_MAX__ 2147483647
#define __INT_WIDTH__ 32
#define __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 1
#define __KERNEL_STRICT_NAMES
#define __KEY_T_TYPE __S32_TYPE
#define __LC_ADDRESS 9
#define __LC_ALL 6
#define __LC_COLLATE 3
#define __LC_CTYPE 0
#define __LC_IDENTIFICATION 12
#define __LC_MEASUREMENT 11
#define __LC_MESSAGES 5
#define __LC_MONETARY 4
#define __LC_NAME 8
#define __LC_NUMERIC 1
#define __LC_PAPER 7
#define __LC_TELEPHONE 10
#define __LC_TIME 2
#define __LDBL_DECIMAL_DIG__ 17
#define __LDBL_DENORM_MIN__ 4.9406564584124654e-324L
#define __LDBL_DIG__ 15
#define __LDBL_EPSILON__ 2.2204460492503131e-16L
#define __LDBL_HAS_DENORM__ 1
#define __LDBL_HAS_INFINITY__ 1
#define __LDBL_HAS_QUIET_NAN__ 1
#define __LDBL_MANT_DIG__ 53
#define __LDBL_MAX_10_EXP__ 308
#define __LDBL_MAX_EXP__ 1024
#define __LDBL_MAX__ 1.7976931348623157e+308L
#define __LDBL_MIN_10_EXP__ (-307)
#define __LDBL_MIN_EXP__ (-1021)
#define __LDBL_MIN__ 2.2250738585072014e-308L
#define __LDBL_REDIR(name,proto) name proto
#define __LDBL_REDIR1(name,proto,alias) name proto
#define __LDBL_REDIR1_NTH(name,proto,alias) name proto __THROW
#define __LDBL_REDIR2_DECL(name)
#define __LDBL_REDIR_DECL(name)
#define __LDBL_REDIR_NTH(name,proto) name proto __THROW
#define __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI 0
#define __LEAF
#define __LEAF_ATTR
#define __LITTLE_ENDIAN 1234
#define __LITTLE_ENDIAN__ 1
#define __LLONG_WIDTH__ 64
#define __LOCK_ALIGNMENT
#define __LONG_LONG_MAX__ 9223372036854775807LL
#define __LONG_LONG_PAIR(HI,LO) LO, HI
#define __LONG_MAX__ 9223372036854775807L
#define __LONG_WIDTH__ 64
#define __LP64__ 1
#define __MODE_T_TYPE __U32_TYPE
#define __N(msgid) (msgid)
#define __NCPUBITS (8 * sizeof (__cpu_mask))
#define __NFDBITS (8 * (int) sizeof (__fd_mask))
#define __NLINK_T_TYPE __SYSCALL_ULONG_TYPE
#define __NO_CTYPE 1
#define __NO_INLINE__ 1
#define __NPU_ARCH__ 3510
#define __NTH(fct) __LEAF_ATTR fct __THROW
#define __NTHNL(fct) fct __THROW
#define __OBJC_BOOL_IS_BOOL 0
#define __OFF64_T_TYPE __SQUAD_TYPE
#define __OFF_T_MATCHES_OFF64_T 1
#define __OFF_T_TYPE __SYSCALL_SLONG_TYPE
#define __ONCE_ALIGNMENT
#define __ONCE_FLAG_INIT { 0 }
#define __OPENCL_MEMORY_SCOPE_ALL_SVM_DEVICES 3
#define __OPENCL_MEMORY_SCOPE_DEVICE 2
#define __OPENCL_MEMORY_SCOPE_SUB_GROUP 4
#define __OPENCL_MEMORY_SCOPE_WORK_GROUP 1
#define __OPENCL_MEMORY_SCOPE_WORK_ITEM 0
#define __ORDER_BIG_ENDIAN__ 4321
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_PDP_ENDIAN__ 3412
#define __P(args) args
#define __PDP_ENDIAN 3412
#define __PID_T_TYPE __S32_TYPE
#define __PMT(args) args
#define __POINTER_WIDTH__ 64
#define __PRAGMA_REDEFINE_EXTNAME 1
#define __PTC__ 1
#define __PTHREAD_MUTEX_HAVE_PREV 1
#define __PTHREAD_MUTEX_INITIALIZER(__kind) 0, 0, 0, 0, __kind, 0, 0, { 0, 0 }
#define __PTHREAD_RWLOCK_ELISION_EXTRA 0, { 0, 0, 0, 0, 0, 0, 0 }
#define __PTHREAD_RWLOCK_INITIALIZER(__flags) 0, 0, 0, 0, 0, 0, 0, 0, __PTHREAD_RWLOCK_ELISION_EXTRA, 0, __flags
#define __PTO_MANUAL__ 1
#define __PTRDIFF_FMTd__ "ld"
#define __PTRDIFF_FMTi__ "li"
#define __PTRDIFF_MAX__ 9223372036854775807L
#define __PTRDIFF_TYPE__ long int
#define __PTRDIFF_WIDTH__ 64
#define __REDIRECT(name,proto,alias) name proto __asm__ (__ASMNAME (#alias))
#define __REDIRECT_LDBL(name,proto,alias) __REDIRECT (name, proto, alias)
#define __REDIRECT_NTH(name,proto,alias) name proto __THROW __asm__ (__ASMNAME (#alias))
#define __REDIRECT_NTHNL(name,proto,alias) name proto __THROWNL __asm__ (__ASMNAME (#alias))
#define __REDIRECT_NTH_LDBL(name,proto,alias) __REDIRECT_NTH (name, proto, alias)
#define __RLIM64_T_TYPE __UQUAD_TYPE
#define __RLIM_T_MATCHES_RLIM64_T 1
#define __RLIM_T_TYPE __SYSCALL_ULONG_TYPE
#define __S16_TYPE short int
#define __S32_TYPE int
#define __S64_TYPE long int
#define __SCHAR_MAX__ 127
#define __SC_THREAD_STACK_MIN_VALUE 75
#define __SHRT_MAX__ 32767
#define __SHRT_WIDTH__ 16
#define __SIG_ATOMIC_MAX__ 2147483647
#define __SIG_ATOMIC_WIDTH__ 32
#define __SIZEOF_DOUBLE__ 8
#define __SIZEOF_FLOAT__ 4
#define __SIZEOF_INT128__ 16
#define __SIZEOF_INT__ 4
#define __SIZEOF_LONG_DOUBLE__ 8
#define __SIZEOF_LONG_LONG__ 8
#define __SIZEOF_LONG__ 8
#define __SIZEOF_POINTER__ 8
#define __SIZEOF_PTHREAD_ATTR_T 56
#define __SIZEOF_PTHREAD_BARRIERATTR_T 4
#define __SIZEOF_PTHREAD_BARRIER_T 32
#define __SIZEOF_PTHREAD_CONDATTR_T 4
#define __SIZEOF_PTHREAD_COND_T 48
#define __SIZEOF_PTHREAD_MUTEXATTR_T 4
#define __SIZEOF_PTHREAD_MUTEX_T 40
#define __SIZEOF_PTHREAD_RWLOCKATTR_T 8
#define __SIZEOF_PTHREAD_RWLOCK_T 56
#define __SIZEOF_PTRDIFF_T__ 8
#define __SIZEOF_SHORT__ 2
#define __SIZEOF_SIZE_T__ 8
#define __SIZEOF_WCHAR_T__ 4
#define __SIZEOF_WINT_T__ 4
#define __SIZE_FMTX__ "lX"
#define __SIZE_FMTo__ "lo"
#define __SIZE_FMTu__ "lu"
#define __SIZE_FMTx__ "lx"
#define __SIZE_MAX__ 18446744073709551615UL
#define __SIZE_TYPE__ long unsigned int
#define __SIZE_WIDTH__ 64
#define __SLONG32_TYPE int
#define __SLONGWORD_TYPE long int
#define __SQUAD_TYPE long int
#define __SSB_BASE_ 0
#define __SSB_SIZE 2048
#define __SSIZE_T_TYPE __SWORD_TYPE
#define __STATFS_MATCHES_STATFS64 1
#define __STDARG_H
#define __STDCPP_DEFAULT_NEW_ALIGNMENT__ 8UL
#define __STDCPP_THREADS__ 1
#define __STDC_HOSTED__ 1
#define __STDC_IEC_559_COMPLEX__ 1
#define __STDC_IEC_559__ 1
#define __STDC_IEC_60559_BFP__ 201404L
#define __STDC_IEC_60559_COMPLEX__ 201404L
#define __STDC_ISO_10646__ 201706L
#define __STDC_UTF_16__ 1
#define __STDC_UTF_32__ 1
#define __STDC__ 1
#define __STDDEF_H
#define __STRICT_ANSI__ 1
#define __STRING(x) #x
#define __SUSECONDS64_T_TYPE __SQUAD_TYPE
#define __SUSECONDS_T_TYPE __SYSCALL_SLONG_TYPE
#define __SWORD_TYPE long int
#define __SYSCALL_SLONG_TYPE __SLONGWORD_TYPE
#define __SYSCALL_ULONG_TYPE __ULONGWORD_TYPE
#define __SYSCALL_WORDSIZE 64
#define __THROW noexcept (true)
#define __THROWNL __THROW
#define __TIME64_T_TYPE __TIME_T_TYPE
#define __TIMER_T_TYPE void *
#define __TIMESIZE __WORDSIZE
#define __TIME_T_TYPE __SYSCALL_SLONG_TYPE
#define __U16_TYPE unsigned short int
#define __U32_TYPE unsigned int
#define __U64_TYPE unsigned long int
#define __UB_BASE 0
#define __UB_SIZE 262144
#define __UID_T_TYPE __U32_TYPE
#define __UINT16_C_SUFFIX__
#define __UINT16_FMTX__ "hX"
#define __UINT16_FMTo__ "ho"
#define __UINT16_FMTu__ "hu"
#define __UINT16_FMTx__ "hx"
#define __UINT16_MAX__ 65535
#define __UINT16_TYPE__ unsigned short
#define __UINT32_C_SUFFIX__ U
#define __UINT32_FMTX__ "X"
#define __UINT32_FMTo__ "o"
#define __UINT32_FMTu__ "u"
#define __UINT32_FMTx__ "x"
#define __UINT32_MAX__ 4294967295U
#define __UINT32_TYPE__ unsigned int
#define __UINT64_C(c) c ## UL
#define __UINT64_C_SUFFIX__ UL
#define __UINT64_FMTX__ "lX"
#define __UINT64_FMTo__ "lo"
#define __UINT64_FMTu__ "lu"
#define __UINT64_FMTx__ "lx"
#define __UINT64_MAX__ 18446744073709551615UL
#define __UINT64_TYPE__ long unsigned int
#define __UINT8_C_SUFFIX__
#define __UINT8_FMTX__ "hhX"
#define __UINT8_FMTo__ "hho"
#define __UINT8_FMTu__ "hhu"
#define __UINT8_FMTx__ "hhx"
#define __UINT8_MAX__ 255
#define __UINT8_TYPE__ unsigned char
#define __UINTMAX_C_SUFFIX__ UL
#define __UINTMAX_FMTX__ "lX"
#define __UINTMAX_FMTo__ "lo"
#define __UINTMAX_FMTu__ "lu"
#define __UINTMAX_FMTx__ "lx"
#define __UINTMAX_MAX__ 18446744073709551615UL
#define __UINTMAX_TYPE__ long unsigned int
#define __UINTMAX_WIDTH__ 64
#define __UINTPTR_FMTX__ "lX"
#define __UINTPTR_FMTo__ "lo"
#define __UINTPTR_FMTu__ "lu"
#define __UINTPTR_FMTx__ "lx"
#define __UINTPTR_MAX__ 18446744073709551615UL
#define __UINTPTR_TYPE__ long unsigned int
#define __UINTPTR_WIDTH__ 64
#define __UINT_FAST16_FMTX__ "hX"
#define __UINT_FAST16_FMTo__ "ho"
#define __UINT_FAST16_FMTu__ "hu"
#define __UINT_FAST16_FMTx__ "hx"
#define __UINT_FAST16_MAX__ 65535
#define __UINT_FAST16_TYPE__ unsigned short
#define __UINT_FAST32_FMTX__ "X"
#define __UINT_FAST32_FMTo__ "o"
#define __UINT_FAST32_FMTu__ "u"
#define __UINT_FAST32_FMTx__ "x"
#define __UINT_FAST32_MAX__ 4294967295U
#define __UINT_FAST32_TYPE__ unsigned int
#define __UINT_FAST64_FMTX__ "lX"
#define __UINT_FAST64_FMTo__ "lo"
#define __UINT_FAST64_FMTu__ "lu"
#define __UINT_FAST64_FMTx__ "lx"
#define __UINT_FAST64_MAX__ 18446744073709551615UL
#define __UINT_FAST64_TYPE__ long unsigned int
#define __UINT_FAST8_FMTX__ "hhX"
#define __UINT_FAST8_FMTo__ "hho"
#define __UINT_FAST8_FMTu__ "hhu"
#define __UINT_FAST8_FMTx__ "hhx"
#define __UINT_FAST8_MAX__ 255
#define __UINT_FAST8_TYPE__ unsigned char
#define __UINT_LEAST16_FMTX__ "hX"
#define __UINT_LEAST16_FMTo__ "ho"
#define __UINT_LEAST16_FMTu__ "hu"
#define __UINT_LEAST16_FMTx__ "hx"
#define __UINT_LEAST16_MAX__ 65535
#define __UINT_LEAST16_TYPE__ unsigned short
#define __UINT_LEAST32_FMTX__ "X"
#define __UINT_LEAST32_FMTo__ "o"
#define __UINT_LEAST32_FMTu__ "u"
#define __UINT_LEAST32_FMTx__ "x"
#define __UINT_LEAST32_MAX__ 4294967295U
#define __UINT_LEAST32_TYPE__ unsigned int
#define __UINT_LEAST64_FMTX__ "lX"
#define __UINT_LEAST64_FMTo__ "lo"
#define __UINT_LEAST64_FMTu__ "lu"
#define __UINT_LEAST64_FMTx__ "lx"
#define __UINT_LEAST64_MAX__ 18446744073709551615UL
#define __UINT_LEAST64_TYPE__ long unsigned int
#define __UINT_LEAST8_FMTX__ "hhX"
#define __UINT_LEAST8_FMTo__ "hho"
#define __UINT_LEAST8_FMTu__ "hhu"
#define __UINT_LEAST8_FMTx__ "hhx"
#define __UINT_LEAST8_MAX__ 255
#define __UINT_LEAST8_TYPE__ unsigned char
#define __ULONG32_TYPE unsigned int
#define __ULONGWORD_TYPE unsigned long int
#define __UQUAD_TYPE unsigned long int
#define __USECONDS_T_TYPE __U32_TYPE
#define __USER_LABEL_PREFIX__
#define __USE_ATFILE 1
#define __USE_DYNAMIC_STACK_SIZE 1
#define __USE_FORTIFY_LEVEL 0
#define __USE_GNU 1
#define __USE_ISOC11 1
#define __USE_ISOC95 1
#define __USE_ISOC99 1
#define __USE_ISOCXX11 1
#define __USE_LARGEFILE 1
#define __USE_LARGEFILE64 1
#define __USE_MISC 1
#define __USE_POSIX 1
#define __USE_POSIX199309 1
#define __USE_POSIX199506 1
#define __USE_POSIX2 1
#define __USE_UNIX98 1
#define __USE_XOPEN 1
#define __USE_XOPEN2K 1
#define __USE_XOPEN2K8 1
#define __USE_XOPEN2K8XSI 1
#define __USE_XOPEN2KXSI 1
#define __USE_XOPEN_EXTENDED 1
#define __UWORD_TYPE unsigned long int
#define __VECTOR_ADDRESS__
#define __VEC_SCOPE__ if(false)
#define __VERSION__ "2026-01-09 10:57:37 +0800 Clang 15.0.5 (clang-ebb840325b82 flang-ebb840325b82)"
#define __WALL 0x40000000
#define __WCHAR_MAX __WCHAR_MAX__
#define __WCHAR_MAX__ 2147483647
#define __WCHAR_MIN (-__WCHAR_MAX - 1)
#define __WCHAR_TYPE__ int
#define __WCHAR_WIDTH__ 32
#define __WCLONE 0x80000000
#define __WCOREDUMP(status) ((status) & __WCOREFLAG)
#define __WCOREFLAG 0x80
#define __WEXITSTATUS(status) (((status) & 0xff00) >> 8)
#define __WIFCONTINUED(status) ((status) == __W_CONTINUED)
#define __WIFEXITED(status) (__WTERMSIG(status) == 0)
#define __WIFSIGNALED(status) (((signed char) (((status) & 0x7f) + 1) >> 1) > 0)
#define __WIFSTOPPED(status) (((status) & 0xff) == 0x7f)
#define __WINT_MAX__ 2147483647
#define __WINT_TYPE__ int
#define __WINT_WIDTH__ 32
#define __WNOTHREAD 0x20000000
#define __WORDSIZE 64
#define __WORDSIZE_TIME64_COMPAT32 1
#define __WSTOPSIG(status) __WEXITSTATUS(status)
#define __WTERMSIG(status) ((status) & 0x7f)
#define __W_CONTINUED 0xffff
#define __W_EXITCODE(ret,sig) ((ret) << 8 | (sig))
#define __W_STOPCODE(sig) ((sig) << 8 | 0x7f)
#define ____FILE_defined 1
#define _____fpos64_t_defined 1
#define _____fpos_t_defined 1
#define ____mbstate_t_defined 1
#define ____sigset_t_defined
#define __aicpu__ __attribute__((cce_aicpu_decl))
#define __align__(n) __attribute__((aligned(n)))
#define __always_inline __inline __attribute__ ((__always_inline__))
#define __attr_access(x)
#define __attr_access_none(argno)
#define __attr_dealloc(dealloc,argno)
#define __attr_dealloc_fclose __attr_dealloc (fclose, 1)
#define __attr_dealloc_free
#define __attribute_alloc_align__(param) __attribute__ ((__alloc_align__ param))
#define __attribute_alloc_size__(params)
#define __attribute_artificial__ __attribute__ ((__artificial__))
#define __attribute_const__ __attribute__ ((__const__))
#define __attribute_copy__(arg)
#define __attribute_deprecated__ __attribute__ ((__deprecated__))
#define __attribute_deprecated_msg__(msg) __attribute__ ((__deprecated__ (msg)))
#define __attribute_format_arg__(x) __attribute__ ((__format_arg__ (x)))
#define __attribute_format_strfmon__(a,b) __attribute__ ((__format__ (__strfmon__, a, b)))
#define __attribute_malloc__ __attribute__ ((__malloc__))
#define __attribute_maybe_unused__ __attribute__ ((__unused__))
#define __attribute_noinline__ __attribute__ ((__noinline__))
#define __attribute_nonnull__(params) __attribute__ ((__nonnull__ params))
#define __attribute_nonstring__
#define __attribute_pure__ __attribute__ ((__pure__))
#define __attribute_returns_twice__ __attribute__ ((__returns_twice__))
#define __attribute_used__ __attribute__ ((__used__))
#define __attribute_warn_unused_result__ __attribute__ ((__warn_unused_result__))
#define __biasbuf__ __attribute__((cce_bias_table_buff))
#define __blkcnt_t_defined
#define __blksize_t_defined
#define __bos(ptr) __builtin_object_size (ptr, __USE_FORTIFY_LEVEL > 1)
#define __bos0(ptr) __builtin_object_size (ptr, 0)
#define __bswap_constant_16(x) ((__uint16_t) ((((x) >> 8) & 0xff) | (((x) & 0xff) << 8)))
#define __bswap_constant_32(x) ((((x) & 0xff000000u) >> 24) | (((x) & 0x00ff0000u) >> 8) | (((x) & 0x0000ff00u) << 8) | (((x) & 0x000000ffu) << 24))
#define __bswap_constant_64(x) ((((x) & 0xff00000000000000ull) >> 56) | (((x) & 0x00ff000000000000ull) >> 40) | (((x) & 0x0000ff0000000000ull) >> 24) | (((x) & 0x000000ff00000000ull) >> 8) | (((x) & 0x00000000ff000000ull) << 8) | (((x) & 0x0000000000ff0000ull) << 24) | (((x) & 0x000000000000ff00ull) << 40) | (((x) & 0x00000000000000ffull) << 56))
#define __builtin_huge_valf32() (__builtin_huge_valf ())
#define __builtin_huge_valf32x() (__builtin_huge_val ())
#define __builtin_huge_valf64() (__builtin_huge_val ())
#define __builtin_huge_valf64x() (__builtin_huge_vall ())
#define __builtin_inff32() (__builtin_inff ())
#define __builtin_inff32x() (__builtin_inf ())
#define __builtin_inff64() (__builtin_inf ())
#define __builtin_inff64x() (__builtin_infl ())
#define __builtin_nanf32(x) (__builtin_nanf (x))
#define __builtin_nanf32x(x) (__builtin_nan (x))
#define __builtin_nanf64(x) (__builtin_nan (x))
#define __builtin_nanf64x(x) (__builtin_nanl (x))
#define __builtin_nansf32(x) (__builtin_nansf (x))
#define __builtin_nansf32x(x) (__builtin_nans (x))
#define __builtin_nansf64(x) (__builtin_nans (x))
#define __builtin_nansf64x(x) (__builtin_nansl (x))
#define __ca__ __attribute__((cce_cube_a))
#define __catch(X) catch(X)
#define __cb__ __attribute__((cce_cube_b))
#define __cbuf__ __attribute__((cce_cube_buff))
#define __cc__ __attribute__((cce_cube_c))
#define __cce_assert(condition,...) do { if (!(condition)) { cce::assert_impl(#condition, __FILE__, __LINE__, ##__VA_ARGS__); return; } } while (0)
#define __check_sync_alias__ __attribute__((check_sync_alias))
#define __clang__ 1
#define __clang_literal_encoding__ "UTF-8"
#define __clang_major__ 15
#define __clang_minor__ 0
#define __clang_patchlevel__ 5
#define __clang_version__ "15.0.5 (clang-ebb840325b82 flang-ebb840325b82)"
#define __clang_wide_literal_encoding__ "UTF-32"
#define __cleanup_fct_attribute
#define __clock_t_defined 1
#define __clockid_t_defined 1
#define __cookie_io_functions_t_defined 1
#define __copyval__ __attribute__((copy_value))
#define __cplusplus 201703L
#define __cpp_aggregate_bases 201603L
#define __cpp_aggregate_nsdmi 201304L
#define __cpp_alias_templates 200704L
#define __cpp_aligned_new 201606L
#define __cpp_attributes 200809L
#define __cpp_binary_literals 201304L
#define __cpp_capture_star_this 201603L
#define __cpp_constexpr 201603L
#define __cpp_constexpr_in_decltype 201711L
#define __cpp_decltype 200707L
#define __cpp_decltype_auto 201304L
#define __cpp_deduction_guides 201703L
#define __cpp_delegating_constructors 200604L
#define __cpp_digit_separators 201309L
#define __cpp_enumerator_attributes 201411L
#define __cpp_exceptions 199711L
#define __cpp_fold_expressions 201603L
#define __cpp_generic_lambdas 201304L
#define __cpp_guaranteed_copy_elision 201606L
#define __cpp_hex_float 201603L
#define __cpp_if_constexpr 201606L
#define __cpp_impl_destroying_delete 201806L
#define __cpp_inheriting_constructors 201511L
#define __cpp_init_captures 201304L
#define __cpp_initializer_lists 200806L
#define __cpp_inline_variables 201606L
#define __cpp_lambdas 200907L
#define __cpp_lib_addressof_constexpr 201603
#define __cpp_lib_allocator_traits_is_always_equal 201411
#define __cpp_lib_array_constexpr 201803L
#define __cpp_lib_bool_constant 201505
#define __cpp_lib_constexpr_char_traits 201611L
#define __cpp_lib_constexpr_string 201611L
#define __cpp_lib_has_unique_object_representations 201606
#define __cpp_lib_incomplete_container_elements 201505
#define __cpp_lib_integral_constant_callable 201304
#define __cpp_lib_is_aggregate 201703
#define __cpp_lib_is_final 201402L
#define __cpp_lib_is_invocable 201703
#define __cpp_lib_is_null_pointer 201309
#define __cpp_lib_is_swappable 201603
#define __cpp_lib_launder 201606
#define __cpp_lib_logical_traits 201510
#define __cpp_lib_make_reverse_iterator 201402
#define __cpp_lib_nonmember_container_access 201411
#define __cpp_lib_result_of_sfinae 201210
#define __cpp_lib_robust_nonmodifying_seq_ops 201304
#define __cpp_lib_string_udls 201304
#define __cpp_lib_string_view 201803L
#define __cpp_lib_transformation_trait_aliases 201304
#define __cpp_lib_transparent_operators 201510
#define __cpp_lib_type_trait_variable_templates 201510L
#define __cpp_lib_void_t 201411
#define __cpp_namespace_attributes 201411L
#define __cpp_nested_namespace_definitions 201411L
#define __cpp_noexcept_function_type 201510L
#define __cpp_nontype_template_args 201411L
#define __cpp_nontype_template_parameter_auto 201606L
#define __cpp_nsdmi 200809L
#define __cpp_range_based_for 201603L
#define __cpp_raw_strings 200710L
#define __cpp_ref_qualifiers 200710L
#define __cpp_return_type_deduction 201304L
#define __cpp_rtti 199711L
#define __cpp_rvalue_references 200610L
#define __cpp_static_assert 201411L
#define __cpp_structured_bindings 201606L
#define __cpp_template_auto 201606L
#define __cpp_threadsafe_static_init 200806L
#define __cpp_unicode_characters 200704L
#define __cpp_unicode_literals 200710L
#define __cpp_user_defined_literals 200809L
#define __cpp_variable_templates 201304L
#define __cpp_variadic_templates 200704L
#define __cpp_variadic_using 201611L
#define __cube__ __attribute__((aic))
#define __daddr_t_defined
#define __dev_t_defined
#define __device_builtin__
#define __device_immutable__ __attribute__((device_immutable))
#define __disable_kernel_type_autoinfer__ __attribute__((disable_kernel_type_autoinfer))
#define __early_read_before_pre_task_done__ __attribute__((cce_early_read_before_pre_task_done))
#define __error_t_defined 1
#define __errordecl(name,msg) extern void name (void)
#define __exctype(name) extern int name (int) __THROW
#define __exctype_l(name) extern int name (int, locale_t) __THROW
#define __extern_always_inline extern __always_inline __attribute__ ((__gnu_inline__))
#define __extern_inline extern __inline __attribute__ ((__gnu_inline__))
#define __f32(x) x##f
#define __f32x(x) x
#define __f64(x) x
#define __f64x(x) x##l
#define __fbuf__ __attribute__((cce_fixpipe_buff))
#define __feof_unlocked_body(_fp) (((_fp)->_flags & _IO_EOF_SEEN) != 0)
#define __ferror_unlocked_body(_fp) (((_fp)->_flags & _IO_ERR_SEEN) != 0)
#define __flexarr []
#define __forceinline__ __inline__ __attribute__((always_inline))
#define __fortified_attr_access(a,o,s)
#define __fortify_function __extern_always_inline __attribute_artificial__
#define __fsblkcnt_t_defined
#define __fsfilcnt_t_defined
#define __get_imm1(imm0) (uint64_t)(imm0)
#define __get_imm2(imm0,imm1) __get_imm1(imm0) + (imm1 * (1 << 16))
#define __get_imm3(imm0,imm1,imm2) __get_imm2(imm0, imm1) + (imm2 * ((uint64_t)1 << 32))
#define __get_imm4(imm0,imm1,imm2,imm3) __get_imm3(imm0, imm1, imm2) + (imm3 * ((uint64_t)1 << 48))
#define __get_imm_va_args(_1,_2,_3,_4,__get_imm_select,...) __get_imm_select
#define __getc_unlocked_body(_fp) (__glibc_unlikely ((_fp)->_IO_read_ptr >= (_fp)->_IO_read_end) ? __uflow (_fp) : *(unsigned char *) (_fp)->_IO_read_ptr++)
#define __gid_t_defined
#define __glibc_c99_flexarr_available 1
#define __glibc_clang_prereq(maj,min) ((__clang_major__ << 16) + __clang_minor__ >= ((maj) << 16) + (min))
#define __glibc_fortify(f,__l,__s,__osz,...) (__glibc_safe_or_unknown_len (__l, __s, __osz) ? __ ## f ## _alias (__VA_ARGS__) : (__glibc_unsafe_len (__l, __s, __osz) ? __ ## f ## _chk_warn (__VA_ARGS__, __osz) : __ ## f ## _chk (__VA_ARGS__, __osz)))
#define __glibc_fortify_n(f,__l,__s,__osz,...) (__glibc_safe_or_unknown_len (__l, __s, __osz) ? __ ## f ## _alias (__VA_ARGS__) : (__glibc_unsafe_len (__l, __s, __osz) ? __ ## f ## _chk_warn (__VA_ARGS__, (__osz) / (__s)) : __ ## f ## _chk (__VA_ARGS__, (__osz) / (__s))))
#define __glibc_has_attribute(attr) __has_attribute (attr)
#define __glibc_has_builtin(name) __has_builtin (name)
#define __glibc_has_extension(ext) __has_extension (ext)
#define __glibc_likely(cond) __builtin_expect ((cond), 1)
#define __glibc_macro_warning(message) __glibc_macro_warning1 (GCC warning message)
#define __glibc_macro_warning1(message) _Pragma (#message)
#define __glibc_objsize(__o) __bos (__o)
#define __glibc_objsize0(__o) __bos0 (__o)
#define __glibc_safe_len_cond(__l,__s,__osz) ((__l) <= (__osz) / (__s))
#define __glibc_safe_or_unknown_len(__l,__s,__osz) (__glibc_unsigned_or_positive (__l) && __builtin_constant_p (__glibc_safe_len_cond ((__SIZE_TYPE__) (__l), __s, __osz)) && __glibc_safe_len_cond ((__SIZE_TYPE__) (__l), __s, __osz))
#define __glibc_unlikely(cond) __builtin_expect ((cond), 0)
#define __glibc_unsafe_len(__l,__s,__osz) (__glibc_unsigned_or_positive (__l) && __builtin_constant_p (__glibc_safe_len_cond ((__SIZE_TYPE__) (__l), __s, __osz)) && !__glibc_safe_len_cond ((__SIZE_TYPE__) (__l), __s, __osz))
#define __glibc_unsigned_or_positive(__l) ((__typeof (__l)) 0 < (__typeof (__l)) -1 || (__builtin_constant_p (__l) && (__l) > 0))
#define __glibcxx_assert(cond) do { __glibcxx_constexpr_assert(cond); } while (false)
#define __glibcxx_class_requires(_a,_b)
#define __glibcxx_class_requires2(_a,_b,_c)
#define __glibcxx_class_requires3(_a,_b,_c,_d)
#define __glibcxx_class_requires4(_a,_b,_c,_d,_e)
#define __glibcxx_constexpr_assert(cond) if (__builtin_is_constant_evaluated() && !bool(cond)) __builtin_unreachable()
#define __glibcxx_function_requires(...)
#define __glibcxx_requires_can_decrement_range(_First1,_Last1,_First2)
#define __glibcxx_requires_can_increment(_First,_Size)
#define __glibcxx_requires_can_increment_range(_First1,_Last1,_First2)
#define __glibcxx_requires_cond(_Cond,_Msg)
#define __glibcxx_requires_heap(_First,_Last)
#define __glibcxx_requires_heap_pred(_First,_Last,_Pred)
#define __glibcxx_requires_irreflexive(_First,_Last)
#define __glibcxx_requires_irreflexive2(_First,_Last)
#define __glibcxx_requires_irreflexive_pred(_First,_Last,_Pred)
#define __glibcxx_requires_irreflexive_pred2(_First,_Last,_Pred)
#define __glibcxx_requires_non_empty_range(_First,_Last)
#define __glibcxx_requires_nonempty()
#define __glibcxx_requires_partitioned_lower(_First,_Last,_Value)
#define __glibcxx_requires_partitioned_lower_pred(_First,_Last,_Value,_Pred)
#define __glibcxx_requires_partitioned_upper(_First,_Last,_Value)
#define __glibcxx_requires_partitioned_upper_pred(_First,_Last,_Value,_Pred)
#define __glibcxx_requires_sorted(_First,_Last)
#define __glibcxx_requires_sorted_pred(_First,_Last,_Pred)
#define __glibcxx_requires_sorted_set(_First1,_Last1,_First2)
#define __glibcxx_requires_sorted_set_pred(_First1,_Last1,_First2,_Pred)
#define __glibcxx_requires_string(_String)
#define __glibcxx_requires_string_len(_String,_Len)
#define __glibcxx_requires_subscript(_N)
#define __glibcxx_requires_valid_range(_First,_Last)
#define __global__ __attribute__((cce_kernel))
#define __gm__ __attribute__((cce_global))
#define __gthrw(name) __gthrw2(__gthrw_ ## name,name,name)
#define __gthrw2(name,name2,type)
#define __gthrw_(name) name
#define __have_pthread_attr_t 1
#define __id_t_defined
#define __in_pipe__(...) __attribute__((in_pipe(#__VA_ARGS__)))
#define __ino64_t_defined
#define __ino_t_defined
#define __inout_pipe__(...) __attribute__((inout_pipe(#__VA_ARGS__)))
#define __intptr_t_defined
#define __isascii(c) (((c) & ~0x7f) == 0)
#define __isctype_l(c,type,locale) ((locale)->__ctype_b[(int) (c)] & (unsigned short int) type)
#define __isleap(year) ((year) % 4 == 0 && ((year) % 100 != 0 || (year) % 400 == 0))
#define __itimerspec_defined 1
#define __jmp_buf_tag_defined 1
#define __key_t_defined
#define __kfc_workspace__ __attribute__((cce_kfc_workspace))
#define __launch_bounds__(N) __attribute__((cce_launch_bounds(N)))
#define __ldiv_t_defined 1
#define __linux__ 1
#define __lldiv_t_defined 1
#define __llvm__ 1
#define __mbstate_t_defined 1
#define __mix__(cube,vec) __attribute__((core_ratio(cube, vec)))
#define __mode_t_defined
#define __need___va_list
#define __nlink_t_defined
#define __no_return__ __attribute__((noreturn))
#define __no_simd_vf_fusion__ __attribute__((no_simd_vf_fusion))
#define __no_specialization__ __attribute__((no_specialization))
#define __nonnull(params) __attribute_nonnull__ (params)
#define __off64_t_defined
#define __off_t_defined
#define __out_pipe__(...) __attribute__((out_pipe(#__VA_ARGS__)))
#define __pid_t_defined
#define __private__
#define __private_extern__ extern
#define __pto_set_flag(src_pipe,dst_pipe) (CceEventIdType) { __builtin_cce_tile_set_flag((unsigned long long)(src_pipe), (unsigned long long)(dst_pipe)) }
#define __pto_wait_flag(src_pipe,dst_pipe,event_id) __builtin_cce_tile_wait_flag((unsigned long long)(src_pipe), (unsigned long long)(dst_pipe), (event_id).__opaque_token)
#define __ptr_t void *
#define __putc_unlocked_body(_ch,_fp) (__glibc_unlikely ((_fp)->_IO_write_ptr >= (_fp)->_IO_write_end) ? __overflow (_fp, (unsigned char) (_ch)) : (unsigned char) (*(_fp)->_IO_write_ptr++ = (_ch)))
#define __restrict_arr
#define __returns_nonnull __attribute__ ((__returns_nonnull__))
#define __sched_priority sched_priority
#define __sigset_t_defined 1
#define __sigsetjmp_cancel(env,savemask) __sigsetjmp ((struct __jmp_buf_tag *) (void *) (env), (savemask))
#define __simd_callee__ __attribute__((cce_simd_callee))
#define __simd_vf__ __attribute__((cce_simd_vf))
#define __simt_callee__ __attribute__((cce_simt_callable))
#define __simt_vf__ __attribute__((cce_simt_entry)) __attribute__((noinline))
#define __ssbuf__ __attribute__((cce_scalar_share_buff))
#define __ssize_t_defined
#define __struct_FILE_defined 1
#define __struct_tm_defined 1
#define __stub___compat_bdflush
#define __stub_chflags
#define __stub_fchflags
#define __stub_gtty
#define __stub_revoke
#define __stub_setlogin
#define __stub_sigreturn
#define __stub_stty
#define __suseconds_t_defined
#define __sync_alias__ __attribute__((sync_alias))
#define __sync_in__ __attribute__((sync_in))
#define __sync_noalias__ __attribute__((sync_noalias))
#define __sync_out__ __attribute__((sync_out))
#define __throw_exception_again throw
#define __time_t_defined 1
#define __timer_t_defined 1
#define __timeval_defined 1
#define __toascii(c) ((c) & 0x7f)
#define __tobody(c,f,a,args) (__extension__ ({ int __res; if (sizeof (c) > 1) { if (__builtin_constant_p (c)) { int __c = (c); __res = __c < -128 || __c > 255 ? __c : (a)[__c]; } else __res = f args; } else __res = (a)[(int) (c)]; __res; }))
#define __try try
#define __u_char_defined
#define __ubuf__ __attribute__((cce_unif_buff))
#define __uid_t_defined
#define __useconds_t_defined
#define __va_copy(d,s) __builtin_va_copy(d,s)
#define __vector__ __attribute__((aiv))
#define __warnattr(msg)
#define __wint_t_defined 1
#define __wur
#define __x86_64__ 0
#define alloca(size) __builtin_alloca (size)
#define be16toh(x) __bswap_16 (x)
#define be32toh(x) __bswap_32 (x)
#define be64toh(x) __bswap_64 (x)
#define block_idx get_block_idx()
#define block_num get_block_num()
#define errno (*__errno_location ())
#define get_imm(...) __get_imm_va_args(__VA_ARGS__, __get_imm4, __get_imm3, __get_imm2, __get_imm1)(__VA_ARGS__)
#define htobe16(x) __bswap_16 (x)
#define htobe32(x) __bswap_32 (x)
#define htobe64(x) __bswap_64 (x)
#define htole16(x) __uint16_identity (x)
#define htole32(x) __uint32_identity (x)
#define htole64(x) __uint64_identity (x)
#define l2_in_main get_l2_in_main()
#define l2_vaddr_base get_l2_vaddr_base()
#define le16toh(x) __uint16_identity (x)
#define le32toh(x) __uint32_identity (x)
#define le64toh(x) __uint64_identity (x)
#define offsetof(t,d) __builtin_offsetof(t, d)
#define pthread_cleanup_pop(execute) __clframe.__setdoit (execute); } while (0)
#define pthread_cleanup_pop_restore_np(execute) __clframe.__restore (); __clframe.__setdoit (execute); } while (0)
#define pthread_cleanup_push(routine,arg) do { __pthread_cleanup_class __clframe (routine, arg)
#define pthread_cleanup_push_defer_np(routine,arg) do { __pthread_cleanup_class __clframe (routine, arg); __clframe.__defer ()
#define sched_priority sched_priority
#define stderr stderr
#define stdin stdin
#define stdout stdout
#define va_arg(ap,type) __builtin_va_arg(ap, type)
#define va_copy(dest,src) __builtin_va_copy(dest, src)
#define va_end(ap) __builtin_va_end(ap)
#define va_start(ap,param) __builtin_va_start(ap, param)
#define vnopxn __builtin_cce_vnopxn
