# The BiShengIR Version number information

if(NOT DEFINED BISHENGIR_VERSION_MAJOR)
  set(BISHENGIR_VERSION_MAJOR 1)
endif()
if(NOT DEFINED BISHENGIR_VERSION_MINOR)
  set(BISHENGIR_VERSION_MINOR 2)
endif()
if(NOT DEFINED BISHENGIR_VERSION_PATCHLEVEL)
  set(BISHENGIR_VERSION_PATCHLEVEL 0)
endif()
if(NOT DEFINED BISHENGIR_VERSION_SUFFIX)
  set(BISHENGIR_VERSION_SUFFIX)
endif()

